import random

# 英単語リスト（例）
words = [
    ("make", "作る"),
    ("take", "連れていく、（時間）がかかる"),
    ("see", "見る、会う"),
    ("work", "働く"),
    ("look", "○○に見える"),
    ("call", "呼ぶ、電話をする"),
    ("last", "続く"),
    ("learn", "学ぶ"),
    ("tell", "話す、教える"),
    ("need", "必要とする"),
    ("enjoy", "楽しむ"),
    ("grow", "育つ"),
    ("give", "与える"),
    ("finish", "終える"),
    ("find", "見つける"),
    ("move", "動く、感動させる"),
    ("send", "送る"),
    ("bring", "持っていく"),
    ("try", "試す"),
    ("decide", "○○することにする"),
    ("hope", "臨む"),
    ("travel", "旅行する"),
    ("invite", "招待する"),
    ("join", "加わる"),
    ("plant", "植える"),
    ("show", "○○を見せる"),
    ("become", "○○になる"),
    ("hold", "（会などを）開く"),
    ("rain", "雨が降る"),
    ("win", "勝ち取る"),
    ("put", "置く"),
    ("wear", "○○を身に着けている"),
    ("keep", "○○にしておく"),
    ("sound", "○○に聞こえる"),
    ("speak", "○○を話す"),
    ("build", "建てる、造る"),
    ("clean", "きれいにする"),
    ("drive", "運転する"),
    ("happen", "起こる"),
    ("remember", "覚えている"),
    ("return", "戻る"),
    ("say", "○○と言う"),
    ("sleep", "眠る"),
    ("paint", "絵具で描く"),
    ("watch", "（注意して）見る"),
    ("worry", "心配する"),
    ("save", "救う、節約する"),
    ("sell", "売る"),
    ("snow", "雪が降る"),
    ("understand", "理解する"),
    ("begin", "始める"),
    ("borrow", "借りる"),
    ("cover", "おおう"),
    ("miss", "さびしく思う、乗り遅れる"),
    ("wait", "待つ"),
    ("arrive", "到着する"),
    ("break", "割る、壊す"),
    ("change", "変える"),
    ("choose", "選ぶ"),
    ("graduate", "卒業する"),
    ("leave", "残す、出発する"),
    ("lend", "貸す"),
    ("feel", "感じる"),
    ("pick", "選ぶ、摘む"),
    ("receive", "受け取る"),
    ("spend", "増やす"),
    ("bake", "焼く"),
    ("draw", "（線）を引く"),
    ("skate", "スケートをする"),
    ("turn", "曲がる"),
    ("p.m.", "午後"),
    ("zoo", "動物園"),
    ("animal", "動物園"),
    ("festival", "祭り"),
    ("elephant", "ゾウ"),
    ("date", "日付"),
    ("subject", "件名、教科"),
    ("store", "店"),
    ("a.m.", "午後"),
    ("toy", "おもちゃ"),
    ("movie", "映画"),
    ("weekend", "週末"),
    ("contest", "コンテスト"),
    ("money", "お金"),
    ("restaurant", "レストラン"),
    ("trip", "旅行する"),
    ("information", "情報"),
    ("kind", "種類"),
    ("dictionary", "辞書"),
    ("food", "料理"),
    ("doctor", "医師"),
    ("job", "仕事"),
    ("kitten", "子猫"),
    ("puppy", "子犬"),
    ("university", "（総合）大学"),
    ("part", "部分"),
    ("place", "場所"),
    ("fun", "楽しいこと"),
    ("parent", "親"),
    ("vacation", "休暇"),
    ("volunteer", "ボランティア"),
    ("band", "（音楽の）バンド"),
    ("chimpanzee", "チンパンジー"),
    ("library", "図書館"),
    ("plant", "計画、予定"),
    ("e-mail", "Eメール"),
    ("hour", "（1）時間"),
    ("practice", "練習"),
    ("son", "息子"),
    ("country", "いなか、国"),
    ("meeting", "会議"),
    ("newspaper", "新聞"),
    ("scientist", "科学者"),
    ("stop", "停留所"),
    ("area", "区域"),
    ("aunt", "おば"),
    ("company", "会社"),
    ("cookie", "クッキー"),
    ("farmer", "脳か"),
    ("garden", "にわ"),
    ("idea", "考え"),
    ("lesson", "けいこ"),
    ("medicine", "薬"),
    ("month", "（暦の）月"),
    ("pumpkin", "カボチャ"),
    ("space", "空間、宇宙"),
    ("station", "（警察）署、駅"),
    ("weather", "天気"),
    ("word", "単語"),
    ("care", "注意、世話"),
    ("chocolate", "チョコレート"),
    ("factory", "工場"),
    ("ice", "氷"),
    ("pizza", "ピザ"),
    ("prize", "賞"),
    ("report", "報告"),
    ("street", "通り"),
    ("visitor", "訪問者"),
    ("way", "方向、方法"),
    ("concert", "演奏会"),
    ("cousin", "いとこ"),
    ("doghouse", "犬小屋"),
    ("group", "団体"),
    ("history", "歴史"),
    ("letter", "手紙"),
    ("minute", "ちょっとの間"),
    ("musician", "音楽家"),
    ("noticde", "通知"),
    ("thing", "もの、こと"),
    ("ticket", "切符"),
    ("tiger", "トラ"),
    ("uncle", "おじ"),
    ("website", "ウェブサイト"),
    ("floor", "床"),
    ("life", "いのち、生活"),
    ("office", "事務所"),
    ("pool", "（スイミング）プール"),
    ("winner", "優勝者"),
    ("building", "ビル、建物"),
    ("college", "（単科）大学"),
    ("daughter", "娘"),
    ("fair", "バザー"),
    ("French", "フランス語"),
    ("future", "未来"),
    ("government", "政府"),
    ("hospital", "病院"),
    ("instrument", "器具、楽器"),
    ("jazz", "ジャズ（音楽）"),
    ("person", "人"),
    ("pie", "パイ"),
    ("Spanish", "スペイン語"),
    ("vegetable", "野菜"),
    ("wife", "妻"),
    ("writer", "作家"),
    ("bookstore", "書店"),
    ("camera", "カメラ"),
    ("clothes", "衣服"),
    ("dish", "料理、皿"),
    ("end", "終わり"),
    ("event", "行事"),
    ("farmer", "農場"),
    ("forest", "森林"),
    ("grandmother", "祖母"),
    ("island", "島"),
    ("magazine", "雑誌"),
    ("member", "一員"),
    ("message", "伝言"),
    ("nature", "自然"),
    ("road", "道"),
    ("speech", "演説"),
    ("supermarket", "スーパーマーケット"),
    ("train", "電車"),
    ("actor", "俳優"),
    ("beach", "海辺"),
    ("color", "色"),
    ("convenience", "便利さ"),
    ("culture", "文科"),
    ("god", "神"),
    ("gym", "体育館"),
    ("husband", "夫"),
    ("machine", "機械"),
    ("paper", "紙"),
    ("plane", "飛行機"),
    ("president", "大統領"),
    ("question", "質問"),
    ("salad", "サラダ"),
    ("tournament", "試合、トーナメント"),
    ("war", "戦争"),
    ("other", "ほかの"),
    ("dear", "親愛なる"),
    ("well", "元気な"),
    ("free", "ひまな、無料の"),
    ("best", "最もよい"),
    ("famous", "有名な"),
    ("special", "特別な"),
    ("little", "少しの"),
    ("sorry", "申し訳なく思って"),
    ("better", "よりよい"),
    ("popular", "人気のある"),
    ("right", "正しい、右の"),
    ("favorite", "お気に入りの"),
    ("sick", "気分の悪い"),
    ("busy", "混雑した、忙しい"),
    ("late", "遅い"),
    ("most", "大部分の"),
    ("beautiful", "美しい"),
    ("close", "近い、親密な"),
    ("different", "異なった、別の、さまざまな"),
    ("enough", "十分な"),
    ("sure", "確信して、確かな"),
    ("ready", "準備ができて"),
    ("glad", "うれしい"),
    ("same", "同じ"),
    ("difficult", "難しい"),
    ("fine", "元気な、晴れた"),
    ("Italian", "イタリアの"),
    ("surprised", "驚いた"),
    ("afraid", "残念ながら、怖がって"),
    ("each", "それぞれの"),
    ("exciting", "わくわくさせる"),
    ("professional", "専門職の"),
    ("wild", "野生の"),
    ("angry", "起こっている"),
    ("another", "別の、もう1つの"),
    ("delicious", "おいしい"),
    ("foreign", "外国の"),
    ("important", "重要な"),
    ("interesting", "興味深い"),
    ("tired", "飽きて、疲れて"),
    ("useful", "役立つ"),
    ("warm", "暖かい"),
    ("hungry", "空腹の"),
    ("lost", "道に迷った"),
    ("main", "おもな"),
    ("native", "ある土地生まれの"),
    ("nervous", "緊張した"),
    ("wrong", "具合が悪い"),
    ("first", "最初に"),
    ("next", "次に"),
    ("also", "～もまた"),
    ("again", "ふたたび、また"),
    ("around", "およそ～、あちこちを"),
    ("before", "以前に"),
    ("hard", "激しく"),
    ("just", "ちょっと、ちょうど"),
    ("often", "しばしば、よく"),
    ("later", "あとで"),
    ("yet", "もう、まだ"),
    ("together", "一緒に"),
    ("ago", "～前に"),
    ("never", "決して～ない、一度も～ない"),
    ("ever", "今までに"),
    ("outside", "外に、外で"),
    ("still", "まだ、今でも"),
    ("tonight", "今夜"),
    ("already", "もう、すでに"),
    ("usually", "たいてい、いつもは"),
    ("early", "早く"),
    ("part-time", "非常勤で、パートタイムで"),
    ("even", "さらに、～でさえ"),
    ("everywhere", "いたるところに、どこでも"),
    ("farmer", "遠方に"),
    ("once", "一度、かつて"),
    ("when", "～するとき"),
    ("if", "もし～ならば"),
    ("because", "～だから"),
    ("than", "～よりも"),
    ("until", "～するまで"),
    ("while", "～する間に"),
    ("by", "によって、のそばに"),
    ("over", "上方に、～より多く"),
    ("between", "（物と物）の間に"),
    ("during", "（～する）間に"),
    ("since", "～以来"),
    ("across", "横切って"),
    ("one", "（1つの）もの"),
    ("all", "すべてのもの"),
    ("anyone", "だれか、だれも（～ない）"),
    ("should", "～すべきだ"),
    ("could", "～することができた"),
    ("must", "～しなければならない"),
]

QUESTIONS = []
qid = 1

for eng, jp in words:

    # ---------- ① 英 → 日（6択） ----------
    wrongs_jp = [w[1] for w in words if w[1] != jp]
    choices = random.sample(wrongs_jp, 5) + [jp]
    random.shuffle(choices)

    QUESTIONS.append({
        "id": qid,
        "type": "choice",
        "q": f"{eng} の意味は？",
        "choices": choices,
        "a": jp
    })
    qid += 1

    # ---------- ② 日 → 英（6択） ----------
    wrongs_eng = [w[0] for w in words if w[0] != eng]
    choices = random.sample(wrongs_eng, 5) + [eng]
    random.shuffle(choices)

    QUESTIONS.append({
        "id": qid,
        "type": "choice",
        "q": f"{jp} は英語で？",
        "choices": choices,
        "a": eng
    })
    qid += 1

    # ---------- ③ 日 → 英（入力） ----------
    QUESTIONS.append({
        "id": qid,
        "type": "input",
        "q": f"{jp} は英語で？（入力）",
        "a": eng
    })
    qid += 1

# 問題順シャッフル
random.shuffle(QUESTIONS)
