import random

QUESTIONS = [
{"id":60000,"q":"a few ～","a":"2つ3つの","choices":["2つ3つの","たくさんの","まったくない","ほとんどの","すべての"]},
{"id":60001,"q":"2つ3つの","a":"a few ～","choices":["a few ～","a lot of ～","none of ～","most of ～","all of ～"]},
{"id":60002,"q":"a glass of ～","a":"コップ1杯の～","choices":["コップ1杯の～","1袋の～","多くの～","少しの～","～に到着する"]},
{"id":60003,"q":"コップ1杯の～","a":"a glass of ～","choices":["a glass of ～","a pair of ～","a slice of ～","be full of ～","after school"]},
{"id":60004,"q":"a little too","a":"少し～すぎる","choices":["少し～すぎる","非常に","世界中で","最初は","～がじょうず"]},
{"id":60005,"q":"少し～すぎる","a":"a little too","choices":["a little too","a lot","as usual","be born","at last"]},
{"id":60006,"q":"a lot","a":"非常に","choices":["非常に","しばらくして","1切れの","放課後に","～と違う"]},
{"id":60007,"q":"非常に","a":"a lot","choices":["a lot","a lot of ～","at first","be famous for ～","agree with ～"]},
{"id":60008,"q":"a lot of ～","a":"多くの～","choices":["多くの～","世界中で","1枚の～","最初は","～することができる"]},
{"id":60009,"q":"多くの～","a":"a lot of ～","choices":["a lot of ～","a piece of ～","be able to ～","after a while","be covered with ～"]},
{"id":60010,"q":"a pair of ～","a":"1組の～","choices":["1組の～","1枚の～","コップ1杯の～","ほかの何か","～でいっぱいである"]},
{"id":60011,"q":"1組の～","a":"a pair of ～","choices":["a pair of ～","a glass of ～","be absent from ～","at school","ask ～ for ～"]},
{"id":60012,"q":"a piece of ～","a":"1かけらの～","choices":["1かけらの～","多くの～","放課後に","いつものように","～してうれしい"]},
{"id":60013,"q":"1かけらの～","a":"a piece of ～","choices":["a piece of ～","a sheet of ～","after school","be glad to do","be born"]},
{"id":60014,"q":"a sheet of ～","a":"1枚の～","choices":["1枚の～","1組の～","世界中で","学校で","～に同意する"]},
{"id":60015,"q":"1枚の～","a":"a sheet of ～","choices":["a sheet of ～","a slice of ～","agree with ～","at school","be full of ～"]},
{"id":60016,"q":"a slice of ～","a":"（薄い）1切れの","choices":["（薄い）1切れの","1かけらの～","最初は","～と違う","～を休んでいる"]},
{"id":60017,"q":"（薄い）1切れの","a":"a slice of ～","choices":["a slice of ～","a little too","be absent from ～","at first","be different from ～"]},
{"id":60018,"q":"after a while","a":"しばらくして","choices":["しばらくして","ついに、とうとう","世界中で","～に到着する","～で有名である"]},
{"id":60019,"q":"しばらくして","a":"after a while","choices":["after a while","after school","arrive in[at,on] ～","all over the world","be famous for ～"]},
{"id":60020,"q":"after school","a":"放課後に","choices":["放課後に","学校で","最初は","ほかの何か","～がじょうず"]},
{"id":60021,"q":"放課後に","a":"after school","choices":["after school","at school","anything else","at first","be good at ～"]},
{"id":60022,"q":"agree with ～","a":"～に同意する","choices":["～に同意する","～で覆われている","～でいっぱいである","生まれる","学校で"]},
{"id":60023,"q":"～に同意する","a":"agree with ～","choices":["agree with ～","be covered with ～","be born","at school","be full of ～"]},
{"id":60024,"q":"all over the world","a":"世界中で","choices":["世界中で","放課後に","しばらくして","～に到着する","～と違う"]},
{"id":60025,"q":"世界中で","a":"all over the world","choices":["all over the world","arrive in[at,on] ～","after a while","be different from ～","after school"]},
{"id":60026,"q":"anything else","a":"ほかの何か","choices":["ほかの何か","1枚の～","ついに、とうとう","学校で","～がじょうず"]},
{"id":60027,"q":"ほかの何か","a":"anything else","choices":["anything else","at last","at school","be good at ～","a sheet of ～"]},
{"id":60028,"q":"arrive in[at,on] ～","a":"～に到着する","choices":["～に到着する","～を休んでいる","～に同意する","最初は","～と違う"]},
{"id":60029,"q":"～に到着する","a":"arrive in[at,on] ～","choices":["arrive in[at,on] ～","agree with ～","be absent from ～","at first","be different from ～"]},
{"id":60030,"q":"as ～ as A can","a":"Aができるだけ","choices":["Aができるだけ","ついに、とうとう","学校で","～することができる","生まれる"]},
{"id":60031,"q":"Aができるだけ","a":"as ～ as A can","choices":["as ～ as A can","be able to ～","at last","at school","be born"]},
{"id":60032,"q":"as usual","a":"いつものように","choices":["いつものように","最初は","世界中で","～でいっぱいである","1組の～"]},
{"id":60033,"q":"いつものように","a":"as usual","choices":["as usual","at first","all over the world","be full of ～","a pair of ～"]},
{"id":60034,"q":"ask ～ for ～","a":"～に～を求める","choices":["～に～を求める","～してうれしい","学校で","～に同意する","1枚の～"]},
{"id":60035,"q":"～に～を求める","a":"ask ～ for ～","choices":["ask ～ for ～","be glad to do","at school","agree with ～","a sheet of ～"]},
{"id":60036,"q":"ask ～ to do","a":"Aに～するように頼む","choices":["Aに～するように頼む","～で覆われている","～を休んでいる","放課後に","非常に"]},
{"id":60037,"q":"Aに～するように頼む","a":"ask ～ to do","choices":["ask ～ to do","be covered with ～","be absent from ～","after school","a lot"]},
{"id":60038,"q":"at first","a":"最初は","choices":["最初は","ついに、とうとう","世界中で","～がじょうず","1切れの"]},
{"id":60039,"q":"最初は","a":"at first","choices":["at first","at last","all over the world","be good at ～","a slice of ～"]},
{"id":60040,"q":"at last","a":"ついに、とうとう","choices":["ついに、とうとう","最初は","学校で","生まれる","多くの～"]},
{"id":60041,"q":"ついに、とうとう","a":"at last","choices":["at last","at first","at school","be born","a lot of ～"]},
{"id":60042,"q":"at school","a":"学校で","choices":["学校で","放課後に","世界中で","～を休んでいる","1組の～"]},
{"id":60043,"q":"学校で","a":"at school","choices":["at school","after school","all over the world","be absent from ～","a pair of ～"]},
{"id":60044,"q":"at the end of ～","a":"～の終わりに","choices":["～の終わりに","～で有名である","少し～すぎる","学校で","コップ1杯の～"]},
{"id":60045,"q":"～の終わりに","a":"at the end of ～","choices":["at the end of ～","be famous for ～","a little too","at school","a glass of ～"]},
{"id":60046,"q":"be able to ～","a":"～することができる","choices":["～することができる","～に到着する","1枚の～","最初は","～でいっぱいである"]},
{"id":60047,"q":"～することができる","a":"be able to ～","choices":["be able to ～","arrive in[at,on] ～","a sheet of ～","at first","be full of ～"]},
{"id":60048,"q":"be absent from ～","a":"～を休んでいる","choices":["～を休んでいる","～に同意する","学校で","1かけらの～","世界中で"]},
{"id":60049,"q":"～を休んでいる","a":"be absent from ～","choices":["be absent from ～","agree with ～","at school","a piece of ～","all over the world"]},
{"id":60050,"q":"be born","a":"生まれる","choices":["生まれる","ついに、とうとう","～に～を求める","1組の～","学校で"]},
{"id":60051,"q":"生まれる","a":"be born","choices":["be born","at last","ask ～ for ～","a pair of ～","at school"]},
{"id":60052,"q":"be covered with ～","a":"～で覆われている","choices":["～で覆われている","～でいっぱいである","世界中で","少し～すぎる","～がじょうず"]},
{"id":60053,"q":"～で覆われている","a":"be covered with ～","choices":["be covered with ～","be full of ～","all over the world","a little too","be good at ～"]},
{"id":60054,"q":"be different from ～","a":"～と違う","choices":["～と違う","～に同意する","学校で","多くの～","1切れの"]},
{"id":60055,"q":"～と違う","a":"be different from ～","choices":["be different from ～","agree with ～","at school","a lot of ～","a slice of ～"]},
{"id":60056,"q":"be famous for ～","a":"～で有名である","choices":["～で有名である","～でいっぱいである","しばらくして","最初は","1枚の～"]},
{"id":60057,"q":"～で有名である","a":"be famous for ～","choices":["be famous for ～","be full of ～","after a while","at first","a sheet of ～"]},
{"id":60058,"q":"be full of ～","a":"～でいっぱいである","choices":["～でいっぱいである","～で覆われている","学校で","非常に","1組の～"]},
{"id":60059,"q":"～でいっぱいである","a":"be full of ～","choices":["be full of ～","be covered with ～","at school","a lot","a pair of ～"]},
{"id":60060,"q":"be glad to do","a":"～してうれしい","choices":["～してうれしい","～することができる","ついに、とうとう","1かけらの～","世界中で"]},
{"id":60061,"q":"～してうれしい","a":"be glad to do","choices":["be glad to do","be able to ～","at last","a piece of ～","all over the world"]},
{"id":60062,"q":"be good at ～","a":"～がじょうず","choices":["～がじょうず","～に到着する","学校で","多くの～","最初は"]},
{"id":60063,"q":"～がじょうず","a":"be good at ～","choices":["be good at ～","arrive in[at,on] ～","at school","a lot of ～","at first"]},
{"id":60064,"q":"be in a hurry","a":"急いでいる","choices":["急いでいる","困っている","外出している","戻る","うまくいく"]},
{"id":60065,"q":"急いでいる","a":"be in a hurry","choices":["be in a hurry","be in trouble","be out","come back","do well"]},
{"id":60066,"q":"be in trouble","a":"困っている","choices":["困っている","急いでいる","～に驚く","帰宅する","お互い"]},
{"id":60067,"q":"困っている","a":"be in trouble","choices":["be in trouble","be in a hurry","be surprised at ～","come home","each other"]},
{"id":60068,"q":"be interested in ～","a":"～に興味がある","choices":["～に興味がある","～を心配している","～に遅れる","実現する","～を見つけ出す"]},
{"id":60069,"q":"～に興味がある","a":"be interested in ～","choices":["be interested in ～","be worried about ～","be late for ～","come true","find out ～"]},
{"id":60070,"q":"be late for ～","a":"～に遅れる","choices":["～に遅れる","～に興味がある","急いでいる","最善を尽くす","～して楽しむ"]},
{"id":60071,"q":"～に遅れる","a":"be late for ～","choices":["be late for ～","be interested in ～","be in a hurry","do one's best","enjoy doing"]},
{"id":60072,"q":"be out","a":"外出している","choices":["外出している","困っている","自分で","倒れる","宿題をする"]},
{"id":60073,"q":"外出している","a":"be out","choices":["be out","be in trouble","by oneself","fall down","do one's homework"]},
{"id":60074,"q":"be proud of ～","a":"～を誇りに思っている","choices":["～を誇りに思っている","～に驚く","～の準備ができている","AとBの間に","戻る"]},
{"id":60075,"q":"～を誇りに思っている","a":"be proud of ～","choices":["be proud of ～","be surprised at ～","be ready for ～","between A and B","come back"]},
{"id":60076,"q":"be ready for ～","a":"～の準備ができている","choices":["～の準備ができている","～する準備ができている","困っている","うまくいく","AをBと交換する"]},
{"id":60077,"q":"～の準備ができている","a":"be ready for ～","choices":["be ready for ～","be ready to do","be in trouble","do well","exchange A for B"]},
{"id":60078,"q":"be ready to do","a":"～する準備ができている","choices":["～する準備ができている","～の準備ができている","～を心配している","帰宅する","十分"]},
{"id":60079,"q":"～する準備ができている","a":"be ready to do","choices":["be ready to do","be ready for ～","be worried about ～","come home","enough"]},
{"id":60080,"q":"be surprised at ～","a":"～に驚く","choices":["～に驚く","～に遅れる","困っている","実現する","最善を尽くす"]},
{"id":60081,"q":"～に驚く","a":"be surprised at ～","choices":["be surprised at ～","be late for ～","be in trouble","come true","do one's best"]},
{"id":60082,"q":"be worried about ～","a":"～を心配している","choices":["～を心配している","～に興味がある","外出している","宿題をする","倒れる"]},
{"id":60083,"q":"～を心配している","a":"be worried about ～","choices":["be worried about ～","be interested in ～","be out","do one's homework","fall down"]},
{"id":60084,"q":"become friends with ～","a":"～と友達になる","choices":["～と友達になる","お互い","自分で","戻る","～して楽しむ"]},
{"id":60085,"q":"～と友達になる","a":"become friends with ～","choices":["become friends with ～","each other","by oneself","come back","enjoy doing"]},
{"id":60086,"q":"between A and B","a":"AとBの間に","choices":["AとBの間に","AとBの両方とも","～に驚く","倒れる","十分"]},
{"id":60087,"q":"AとBの間に","a":"between A and B","choices":["between A and B","both A and B","be surprised at ～","fall down","enough"]},
{"id":60088,"q":"both A and B","a":"AとBの両方とも","choices":["AとBの両方とも","AとBの間に","困っている","実現する","～を見つけ出す"]},
{"id":60089,"q":"AとBの両方とも","a":"both A and B","choices":["both A and B","between A and B","be in trouble","come true","find out ～"]},
{"id":60090,"q":"both of ～","a":"～の両方とも（2人とも）","choices":["～の両方とも（2人とも）","自分で","急いでいる","うまくいく","～することに決める"]},
{"id":60091,"q":"～の両方とも（2人とも）","a":"both of ～","choices":["both of ～","by oneself","be in a hurry","do well","decide to do"]},
{"id":60092,"q":"by oneself","a":"自分で","choices":["自分で","お互い","外出している","帰宅する","最善を尽くす"]},
{"id":60093,"q":"自分で","a":"by oneself","choices":["by oneself","each other","be out","come home","do one's best"]},
{"id":60094,"q":"clean up ～","a":"～をきれいに片付ける","choices":["～をきれいに片付ける","～を見つけ出す","困っている","倒れる","～にとっては十分"]},
{"id":60095,"q":"～をきれいに片付ける","a":"clean up ～","choices":["clean up ～","find out ～","be in trouble","fall down","enough for ～"]},
{"id":60096,"q":"come back","a":"戻る","choices":["戻る","帰宅する","実現する","急いでいる","AをBと交換する"]},
{"id":60097,"q":"戻る","a":"come back","choices":["come back","come home","come true","be in a hurry","exchange A for B"]},
{"id":60098,"q":"come home","a":"帰宅する","choices":["帰宅する","戻る","外出している","最善を尽くす","お互い"]},
{"id":60099,"q":"帰宅する","a":"come home","choices":["come home","come back","be out","do one's best","each other"]},
{"id":60100,"q":"come true","a":"実現する","choices":["実現する","戻る","～に驚く","宿題をする","十分"]},
{"id":60101,"q":"実現する","a":"come true","choices":["come true","come back","be surprised at ～","do one's homework","enough"]},
{"id":60102,"q":"decide to do","a":"～することに決める","choices":["～することに決める","～する準備ができている","急いでいる","お互い","～にとっては十分"]},
{"id":60103,"q":"～することに決める","a":"decide to do","choices":["decide to do","be ready to do","be in a hurry","each other","enough for ～"]},
{"id":60104,"q":"do one's best","a":"最善を尽くす","choices":["最善を尽くす","宿題をする","うまくいく","困っている","～を見つけ出す"]},
{"id":60105,"q":"最善を尽くす","a":"do one's best","choices":["do one's best","do one's homework","do well","be in trouble","find out ～"]},
{"id":60106,"q":"do one's homework","a":"宿題をする","choices":["宿題をする","最善を尽くす","自分で","実現する","～して楽しむ"]},
{"id":60107,"q":"宿題をする","a":"do one's homework","choices":["do one's homework","do one's best","by oneself","come true","enjoy doing"]},
{"id":60108,"q":"do well","a":"うまくいく","choices":["うまくいく","戻る","～に遅れる","AとBの両方とも","～するのに十分"]},
{"id":60109,"q":"うまくいく","a":"do well","choices":["do well","come back","be late for ～","both A and B","enough to do"]},
{"id":60110,"q":"each other","a":"お互い","choices":["お互い","～と友達になる","帰宅する","急いでいる","～を誇りに思っている"]},
{"id":60111,"q":"お互い","a":"each other","choices":["each other","become friends with ～","come home","be in a hurry","be proud of ～"]},
{"id":60112,"q":"enjoy doing","a":"～して楽しむ","choices":["～して楽しむ","～することに決める","困っている","宿題をする","AをBと交換する"]},
{"id":60113,"q":"～して楽しむ","a":"enjoy doing","choices":["enjoy doing","decide to do","be in trouble","do one's homework","exchange A for B"]},
{"id":60114,"q":"enough for ～","a":"～にとっては十分","choices":["～にとっては十分","～するのに十分","自分で","実現する","倒れる"]},
{"id":60115,"q":"～にとっては十分","a":"enough for ～","choices":["enough for ～","enough to do","by oneself","come true","fall down"]},
{"id":60116,"q":"enough to do","a":"～するのに十分","choices":["～するのに十分","～にとっては十分","急いでいる","戻る","～を見つけ出す"]},
{"id":60117,"q":"～するのに十分","a":"enough to do","choices":["enough to do","enough for ～","be in a hurry","come back","find out ～"]},
{"id":60118,"q":"exchange A for B","a":"AをBと交換する","choices":["AをBと交換する","AとBの間に","～を心配している","最善を尽くす","帰宅する"]},
{"id":60119,"q":"AをBと交換する","a":"exchange A for B","choices":["exchange A for B","between A and B","be worried about ～","do one's best","come home"]},
{"id":60120,"q":"fall down","a":"倒れる","choices":["倒れる","戻る","外出している","宿題をする","～を誇りに思っている"]},
{"id":60121,"q":"倒れる","a":"fall down","choices":["fall down","come back","be out","do one's homework","be proud of ～"]},
{"id":60122,"q":"find out ～","a":"～を見つけ出す","choices":["～を見つけ出す","～をきれいに片付ける","実現する","お互い","～する準備ができている"]},
{"id":60123,"q":"～を見つけ出す","a":"find out ～","choices":["find out ～","clean up ～","come true","each other","be ready to do"]},
{"id":60124,"q":"finish doing","a":"～し終える","choices":["～し終える","まず最初に","旅行に出かける","寝る","満点をとる"]},
{"id":60125,"q":"～し終える","a":"finish doing","choices":["finish doing","first of all","go on a trip","go to bed","get a perfect score"]},
{"id":60126,"q":"first of all","a":"まず最初に","choices":["まず最初に","たとえば","帰宅する","買い物に行く","寒くなる"]},
{"id":60127,"q":"まず最初に","a":"first of all","choices":["first of all","for example","go home","go shopping","get cold"]},
{"id":60128,"q":"for a long time","a":"長い間","choices":["長い間","初めて","暗くなる","仕事に行く","散歩に行く"]},
{"id":60129,"q":"長い間","a":"for a long time","choices":["for a long time","for the first time","get dark","go to work","go for a walk"]},
{"id":60130,"q":"for example","a":"たとえば","choices":["たとえば","まず最初に","帰宅する","釣りに行く","空腹になる"]},
{"id":60131,"q":"たとえば","a":"for example","choices":["for example","first of all","go back home","go fishing","get hungry"]},
{"id":60132,"q":"for the first time","a":"初めて","choices":["初めて","長い間","（乗り物を）乗る","映画を見に行く","よい成績をとる"]},
{"id":60133,"q":"初めて","a":"for the first time","choices":["for the first time","for a long time","get on ～","go to see a movie","get a good grade"]},
{"id":60134,"q":"from A to B","a":"AからBまで","choices":["AからBまで","Aを車に乗せる","～に着く","寝る","暗くなる"]},
{"id":60135,"q":"AからBまで","a":"from A to B","choices":["from A to B","give A a ride","get to ～","go to bed","get dark"]},
{"id":60136,"q":"get a good grade","a":"よい成績をとる","choices":["よい成績をとる","満点をとる","空腹になる","旅行に出かける","まず最初に"]},
{"id":60137,"q":"よい成績をとる","a":"get a good grade","choices":["get a good grade","get a perfect score","get hungry","go on a trip","first of all"]},
{"id":60138,"q":"get a perfect score","a":"満点をとる","choices":["満点をとる","よい成績をとる","寒くなる","買い物に行く","長い間"]},
{"id":60139,"q":"満点をとる","a":"get a perfect score","choices":["get a perfect score","get a good grade","get cold","go shopping","for a long time"]},
{"id":60140,"q":"get cold","a":"寒くなる","choices":["寒くなる","暗くなる","帰宅する","散歩に行く","初めて"]},
{"id":60141,"q":"寒くなる","a":"get cold","choices":["get cold","get dark","get home","go for a walk","for the first time"]},
{"id":60142,"q":"get dark","a":"暗くなる","choices":["暗くなる","寒くなる","（乗り物を）降りる","仕事に行く","たとえば"]},
{"id":60143,"q":"暗くなる","a":"get dark","choices":["get dark","get cold","get off ～","go to work","for example"]},
{"id":60144,"q":"get home","a":"帰宅する","choices":["帰宅する","仕事に行く","まっすぐに歩いて行く","長い間","満点をとる"]},
{"id":60145,"q":"帰宅する","a":"get home","choices":["get home","go to work","go walk straight","for a long time","get a perfect score"]},
{"id":60146,"q":"get hungry","a":"空腹になる","choices":["空腹になる","寒くなる","釣りに行く","映画を見に行く","まず最初に"]},
{"id":60147,"q":"空腹になる","a":"get hungry","choices":["get hungry","get cold","go fishing","go to see a movie","first of all"]},
{"id":60148,"q":"get off ～","a":"（乗り物を）降りる","choices":["（乗り物を）降りる","（乗り物に）乗る","帰宅する","散歩に行く","初めて"]},
{"id":60149,"q":"（乗り物を）降りる","a":"get off ～","choices":["get off ～","get on ～","get home","go for a walk","for the first time"]},
{"id":60150,"q":"get on ～","a":"（乗り物に）乗る","choices":["（乗り物に）乗る","（乗り物を）降りる","～に着く","旅行に出かける","長い間"]},
{"id":60151,"q":"（乗り物に）乗る","a":"get on ～","choices":["get on ～","get off ～","get to ～","go on a trip","for a long time"]},
{"id":60152,"q":"get to ～","a":"～に着く","choices":["～に着く","AからBまで","帰宅する","寝る","たとえば"]},
{"id":60153,"q":"～に着く","a":"get to ～","choices":["get to ～","from A to B","get home","go to bed","for example"]},
{"id":60154,"q":"give A a ride","a":"Aを車に乗せる","choices":["Aを車に乗せる","AからBまで","買い物に行く","空腹になる","初めて"]},
{"id":60155,"q":"Aを車に乗せる","a":"give A a ride","choices":["give A a ride","from A to B","go shopping","get hungry","for the first time"]},
{"id":60156,"q":"go and do","a":"～しに行く","choices":["～しに行く","帰宅する","釣りに行く","仕事に行く","満点をとる"]},
{"id":60157,"q":"～しに行く","a":"go and do","choices":["go and do","go home","go fishing","go to work","get a perfect score"]},
{"id":60158,"q":"go back home","a":"帰宅する","choices":["帰宅する","散歩に行く","暗くなる","まず最初に","よい成績をとる"]},
{"id":60159,"q":"帰宅する","a":"go back home","choices":["go back home","go for a walk","get dark","first of all","get a good grade"]},
{"id":60160,"q":"go fishing","a":"釣りに行く","choices":["釣りに行く","買い物に行く","空腹になる","旅行に出かける","長い間"]},
{"id":60161,"q":"釣りに行く","a":"go fishing","choices":["go fishing","go shopping","get hungry","go on a trip","for a long time"]},
{"id":60162,"q":"go for a walk","a":"散歩に行く","choices":["散歩に行く","周遊旅行に出かける","帰宅する","寒くなる","初めて"]},
{"id":60163,"q":"散歩に行く","a":"go for a walk","choices":["go for a walk","go on a tour","go home","get cold","for the first time"]},
{"id":60164,"q":"go home","a":"帰宅する","choices":["帰宅する","仕事に行く","暗くなる","まず最初に","満点をとる"]},
{"id":60165,"q":"帰宅する","a":"go home","choices":["go home","go to work","get dark","first of all","get a perfect score"]},
{"id":60166,"q":"go on a tour","a":"周遊旅行に出かける","choices":["周遊旅行に出かける","旅行に出かける","買い物に行く","空腹になる","たとえば"]},
{"id":60167,"q":"周遊旅行に出かける","a":"go on a tour","choices":["go on a tour","go on a trip","go shopping","get hungry","for example"]},
{"id":60168,"q":"go on a trip","a":"旅行に出かける","choices":["旅行に出かける","周遊旅行に出かける","散歩に行く","暗くなる","まず最初に"]},
{"id":60169,"q":"旅行に出かける","a":"go on a trip","choices":["go on a trip","go on a tour","go for a walk","get dark","first of all"]},
{"id":60170,"q":"go out for ～","a":"～のために出かける","choices":["～のために出かける","買い物に行く","空腹になる","満点をとる","長い間"]},
{"id":60171,"q":"～のために出かける","a":"go out for ～","choices":["go out for ～","go shopping","get hungry","get a perfect score","for a long time"]},
{"id":60172,"q":"go shopping","a":"買い物に行く","choices":["買い物に行く","釣りに行く","帰宅する","寒くなる","たとえば"]},
{"id":60173,"q":"買い物に行く","a":"go shopping","choices":["go shopping","go fishing","go home","get cold","for example"]},
{"id":60174,"q":"go walk straight","a":"まっすぐに歩いて行く","choices":["まっすぐに歩いて行く","寝る","～に着く","旅行に出かける","初めて"]},
{"id":60175,"q":"まっすぐに歩いて行く","a":"go walk straight","choices":["go walk straight","go to bed","get to ～","go on a trip","for the first time"]},
{"id":60176,"q":"go to bed","a":"寝る","choices":["寝る","帰宅する","暗くなる","買い物に行く","まず最初に"]},
{"id":60177,"q":"寝る","a":"go to bed","choices":["go to bed","go home","get dark","go shopping","first of all"]},
{"id":60178,"q":"go to see a movie","a":"映画を見に行く","choices":["映画を見に行く","医師に診てもらいに行く","釣りに行く","空腹になる","長い間"]},
{"id":60179,"q":"映画を見に行く","a":"go to see a movie","choices":["go to see a movie","go to the doctor","go fishing","get hungry","for a long time"]},
{"id":60180,"q":"go to the doctor","a":"医師に診てもらいに行く","choices":["医師に診てもらいに行く","映画を見に行く","帰宅する","寒くなる","たとえば"]},
{"id":60181,"q":"医師に診てもらいに行く","a":"go to the doctor","choices":["go to the doctor","go to see a movie","go home","get cold","for example"]},
{"id":60182,"q":"go to work","a":"仕事に行く","choices":["仕事に行く","帰宅する","暗くなる","旅行に出かける","満点をとる"]},
{"id":60183,"q":"仕事に行く","a":"go to work","choices":["go to work","go home","get dark","go on a trip","get a perfect score"]},
{"id":60184,"q":"graduate from ～","a":"～を卒業する","choices":["～を卒業する","大人になる","昼食をとる","急ぐ","先週"]},
{"id":60185,"q":"～を卒業する","a":"graduate from ～","choices":["graduate from ～","grow up","have lunch","hurry up","last week"]},
{"id":60186,"q":"grow up","a":"大人になる","choices":["大人になる","楽しく過ごす","伝言を残す","午前中に","風邪をひいている"]},
{"id":60187,"q":"大人になる","a":"grow up","choices":["grow up","have a great time","leave a message","in the morning","have a cold"]},
{"id":60188,"q":"have a chance to do","a":"～する機会がある","choices":["～する機会がある","～する時間がある","楽しむ","世界で","急ぐ"]},
{"id":60189,"q":"～する機会がある","a":"have a chance to do","choices":["have a chance to do","have time to do","have fun","in the world","hurry up"]},
{"id":60190,"q":"have a cold","a":"風邪をひいている","choices":["風邪をひいている","楽しく過ごす","先週","～の前で","昼食をとる"]},
{"id":60191,"q":"風邪をひいている","a":"have a cold","choices":["have a cold","have a great time","last week","in front of ～","have lunch"]},
{"id":60192,"q":"have a great time","a":"楽しく過ごす","choices":["楽しく過ごす","楽しむ","大人になる","～の真ん中に","伝言を残す"]},
{"id":60193,"q":"楽しく過ごす","a":"have a great time","choices":["have a great time","have fun","grow up","in the middle of ～","leave a message"]},
{"id":60194,"q":"have been to ～","a":"～に行ったことがある","choices":["～に行ったことがある","～に行ったことがない","～を卒業する","世界で","風邪をひいている"]},
{"id":60195,"q":"～に行ったことがある","a":"have been to ～","choices":["have been to ～","have never been to ～","graduate from ～","in the world","have a cold"]},
{"id":60196,"q":"have enough A to do ～","a":"～するのに十分なAがある","choices":["～するのに十分なAがある","～する方法","楽しむ","先週","急ぐ"]},
{"id":60197,"q":"～するのに十分なAがある","a":"have enough A to do ～","choices":["have enough A to do ～","how to do","have fun","last week","hurry up"]},
{"id":60198,"q":"have fun","a":"楽しむ","choices":["楽しむ","楽しく過ごす","昼食をとる","午前中に","～の意見では"]},
{"id":60199,"q":"楽しむ","a":"have fun","choices":["have fun","have a great time","have lunch","in the morning","in one's opinion"]},
{"id":60200,"q":"have lunch","a":"昼食をとる","choices":["昼食をとる","楽しむ","伝言を残す","世界で","風邪をひいている"]},
{"id":60201,"q":"昼食をとる","a":"have lunch","choices":["have lunch","have fun","leave a message","in the world","have a cold"]},
{"id":60202,"q":"have never been to ～","a":"～に行ったことがない","choices":["～に行ったことがない","～に行ったことがある","急ぐ","先週","大人になる"]},
{"id":60203,"q":"～に行ったことがない","a":"have never been to ～","choices":["have never been to ～","have been to ～","hurry up","last week","grow up"]},
{"id":60204,"q":"have time to do","a":"～する時間がある","choices":["～する時間がある","～する機会がある","楽しむ","午前中に","昼食をとる"]},
{"id":60205,"q":"～する時間がある","a":"have time to do","choices":["have time to do","have a chance to do","have fun","in the morning","have lunch"]},
{"id":60206,"q":"have to do","a":"～しなければならない","choices":["～しなければならない","～する方法","急ぐ","世界で","楽しく過ごす"]},
{"id":60207,"q":"～しなければならない","a":"have to do","choices":["have to do","how to do","hurry up","in the world","have a great time"]},
{"id":60208,"q":"how long ～","a":"どのくらいの長さで","choices":["どのくらいの長さで","何回～","先週","～の前で","伝言を残す"]},
{"id":60209,"q":"どのくらいの長さで","a":"how long ～","choices":["how long ～","how many times ～","last week","in front of ～","leave a message"]},
{"id":60210,"q":"how many times ～","a":"何回～","choices":["何回～","どのくらいの頻度で～","昼食をとる","大人になる","楽しむ"]},
{"id":60211,"q":"何回～","a":"how many times ～","choices":["how many times ～","how often ～","have lunch","grow up","have fun"]},
{"id":60212,"q":"how often ～","a":"どのくらいの頻度で～","choices":["どのくらいの頻度で～","何回～","風邪をひいている","急ぐ","世界で"]},
{"id":60213,"q":"どのくらいの頻度で～","a":"how often ～","choices":["how often ～","how many times ～","have a cold","hurry up","in the world"]},
{"id":60214,"q":"how to do","a":"～する方法","choices":["～する方法","～しなければならない","先週","～の真ん中に","楽しむ"]},
{"id":60215,"q":"～する方法","a":"how to do","choices":["how to do","have to do","last week","in the middle of ～","have fun"]},
{"id":60216,"q":"hurry up","a":"急ぐ","choices":["急ぐ","伝言を残す","風邪をひいている","大人になる","世界で"]},
{"id":60217,"q":"急ぐ","a":"hurry up","choices":["hurry up","leave a message","have a cold","grow up","in the world"]},
{"id":60218,"q":"I'd like to do","a":"～したい","choices":["～したい","～する方法","楽しむ","先週","昼食をとる"]},
{"id":60219,"q":"～したい","a":"I'd like to do","choices":["I'd like to do","how to do","have fun","last week","have lunch"]},
{"id":60220,"q":"in front of ～","a":"～の前で","choices":["～の前で","～の真ん中に","楽しく過ごす","急ぐ","大人になる"]},
{"id":60221,"q":"～の前で","a":"in front of ～","choices":["in front of ～","in the middle of ～","have a great time","hurry up","grow up"]},
{"id":60222,"q":"in one's opinion","a":"～の意見では","choices":["～の意見では","世界で","楽しむ","風邪をひいている","先週"]},
{"id":60223,"q":"～の意見では","a":"in one's opinion","choices":["in one's opinion","in the world","have fun","have a cold","last week"]},
{"id":60224,"q":"in the middle of ～","a":"～の真ん中に","choices":["～の真ん中に","～の前で","昼食をとる","伝言を残す","楽しく過ごす"]},
{"id":60225,"q":"～の真ん中に","a":"in the middle of ～","choices":["in the middle of ～","in front of ～","have lunch","leave a message","have a great time"]},
{"id":60226,"q":"in the morning","a":"午前中に","choices":["午前中に","世界で","大人になる","急ぐ","～しなければならない"]},
{"id":60227,"q":"午前中に","a":"in the morning","choices":["in the morning","in the world","grow up","hurry up","have to do"]},
{"id":60228,"q":"in the world","a":"世界で","choices":["世界で","午前中に","楽しむ","風邪をひいている","先週"]},
{"id":60229,"q":"世界で","a":"in the world","choices":["in the world","in the morning","have fun","have a cold","last week"]},
{"id":60230,"q":"invete A to B","a":"AをBに招待する","choices":["AをBに招待する","Aを家に置き忘れる","急ぐ","楽しく過ごす","～する機会がある"]},
{"id":60231,"q":"AをBに招待する","a":"invete A to B","choices":["invete A to B","leave A at home","hurry up","have a great time","have a chance to do"]},
{"id":60232,"q":"It takes A a hour to do ～","a":"Aが～するのに1時間かかりました","choices":["Aが～するのに1時間かかりました","～する時間がある","先週","楽しむ","～の前で"]},
{"id":60233,"q":"Aが～するのに1時間かかりました","a":"It takes A a hour to do ～","choices":["It takes A a hour to do ～","have time to do","last week","have fun","in front of ～"]},
{"id":60234,"q":"last week","a":"先週","choices":["先週","午前中に","風邪をひいている","大人になる","急ぐ"]},
{"id":60235,"q":"先週","a":"last week","choices":["last week","in the morning","have a cold","grow up","hurry up"]},
{"id":60236,"q":"laugh at ～","a":"～を聞いて笑う","choices":["～を聞いて笑う","伝言を残す","楽しく過ごす","昼食をとる","世界で"]},
{"id":60237,"q":"～を聞いて笑う","a":"laugh at ～","choices":["laugh at ～","leave a message","have a great time","have lunch","in the world"]},
{"id":60238,"q":"leave A at home","a":"Aを家に置き忘れる","choices":["Aを家に置き忘れる","AをBに招待する","急ぐ","楽しむ","先週"]},
{"id":60239,"q":"Aを家に置き忘れる","a":"leave A at home","choices":["leave A at home","invete A to B","hurry up","have fun","last week"]},
{"id":60240,"q":"leave a message","a":"伝言を残す","choices":["伝言を残す","～を聞いて笑う","楽しく過ごす","風邪をひいている","午前中に"]},
{"id":60241,"q":"伝言を残す","a":"leave a message","choices":["leave a message","laugh at ～","have a great time","have a cold","in the morning"]},
{"id":60242,"q":"look around","a":"辺りを見回す","choices":["辺りを見回す","～を探す","逃げ去る","ちょうど今","週末に"]},
{"id":60243,"q":"辺りを見回す","a":"look around","choices":["look around","look for ～","run away","right now","on weekends"]},
{"id":60244,"q":"look for ～","a":"～を探す","choices":["～を探す","辺りを見回す","貯金する","仕事で","試験に合格する"]},
{"id":60245,"q":"～を探す","a":"look for ～","choices":["look for ～","look around","save money","on business","pass the exam"]},
{"id":60246,"q":"look forward to doing A","a":"～するのを楽しみに待つ","choices":["～するのを楽しみに待つ","～する必要がある","もう1つの","この近くに","賞を受ける"]},
{"id":60247,"q":"～するのを楽しみに待つ","a":"look forward to doing A","choices":["look forward to doing A","need to do","one more","near here","receive a prize"]},
{"id":60248,"q":"look well","a":"元気そうに見える","choices":["元気そうに見える","まったく～ない","仕事で","右手に","貯金する"]},
{"id":60249,"q":"元気そうに見える","a":"look well","choices":["look well","not ～ at all","on business","on one's right","save money"]},
{"id":60250,"q":"lots of ～","a":"多くの～","choices":["多くの～","～のほとんど","もう1つの","この近くに","試験に合格する"]},
{"id":60251,"q":"多くの～","a":"lots of ～","choices":["lots of ～","most of ～","one more","near here","pass the exam"]},
{"id":60252,"q":"make a speech","a":"スピーチをする","choices":["スピーチをする","賞を受ける","辺りを見回す","週末に","逃げ去る"]},
{"id":60253,"q":"スピーチをする","a":"make a speech","choices":["make a speech","receive a prize","look around","on weekends","run away"]},
{"id":60254,"q":"more than ～","a":"～より多い","choices":["～より多い","～の1つ","仕事で","ちょうど今","貯金する"]},
{"id":60255,"q":"～より多い","a":"more than ～","choices":["more than ～","one of ～","on business","right now","save money"]},
{"id":60256,"q":"most of ～","a":"～のほとんど","choices":["～のほとんど","多くの～","もう1つの","試験に合格する","辺りを見回す"]},
{"id":60257,"q":"～のほとんど","a":"most of ～","choices":["most of ～","lots of ～","one more","pass the exam","look around"]},
{"id":60258,"q":"move to ～","a":"～に移動する","choices":["～に移動する","～を車で迎えに来る","右手に","この近くに","賞を受ける"]},
{"id":60259,"q":"～に移動する","a":"move to ～","choices":["move to ～","pick up ～","on one's right","near here","receive a prize"]},
{"id":60260,"q":"near here","a":"この近くに","choices":["この近くに","向こうに","逃げ去る","ちょうど今","貯金する"]},
{"id":60261,"q":"この近くに","a":"near here","choices":["near here","over ther","run away","right now","save money"]},
{"id":60262,"q":"need to do","a":"～する必要がある","choices":["～する必要がある","～しなくてよい","仕事で","週末に","辺りを見回す"]},
{"id":60263,"q":"～する必要がある","a":"need to do","choices":["need to do","not have to do","on business","on weekends","look around"]},
{"id":60264,"q":"not ～ at all","a":"まったく～ない","choices":["まったく～ない","まだ～ない","右手に","向こうに","試験に合格する"]},
{"id":60265,"q":"まったく～ない","a":"not ～ at all","choices":["not ～ at all","not ～ yet","on one's right","over ther","pass the exam"]},
{"id":60266,"q":"not ～ yet","a":"まだ～ない","choices":["まだ～ない","まったく～ない","仕事で","貯金する","賞を受ける"]},
{"id":60267,"q":"まだ～ない","a":"not ～ yet","choices":["not ～ yet","not ～ at all","on business","save money","receive a prize"]},
{"id":60268,"q":"not have to do","a":"～しなくてよい","choices":["～しなくてよい","～する必要がある","この近くに","辺りを見回す","逃げ去る"]},
{"id":60269,"q":"～しなくてよい","a":"not have to do","choices":["not have to do","need to do","near here","look around","run away"]},
{"id":60270,"q":"not only A but also B","a":"AだけでなくBも","choices":["AだけでなくBも","～より多い","もう1つの","仕事で","ちょうど今"]},
{"id":60271,"q":"AだけでなくBも","a":"not only A but also B","choices":["not only A but also B","more than ～","one more","on business","right now"]},
{"id":60272,"q":"on business","a":"仕事で","choices":["仕事で","右手に","～を探す","賞を受ける","向こうに"]},
{"id":60273,"q":"仕事で","a":"on business","choices":["on business","on one's right","look for ～","receive a prize","over ther"]},
{"id":60274,"q":"on one's right","a":"右手に","choices":["右手に","家に帰る途中で","～を車で迎えに来る","週末に","試験に合格する"]},
{"id":60275,"q":"右手に","a":"on one's right","choices":["on one's right","on one's way home","pick up ～","on weekends","pass the exam"]},
{"id":60276,"q":"on one's way home","a":"家に帰る途中で","choices":["家に帰る途中で","～へ行く途中","辺りを見回す","貯金する","この近くに"]},
{"id":60277,"q":"家に帰る途中で","a":"on one's way home","choices":["on one's way home","on one's way to ～","look around","save money","near here"]},
{"id":60278,"q":"on one's way to ～","a":"～へ行く途中","choices":["～へ行く途中","家に帰る途中で","向こうに","ちょうど今","賞を受ける"]},
{"id":60279,"q":"～へ行く途中","a":"on one's way to ～","choices":["on one's way to ～","on one's way home","over ther","right now","receive a prize"]},
{"id":60280,"q":"on weekends","a":"週末に","choices":["週末に","仕事で","逃げ去る","辺りを見回す","試験に合格する"]},
{"id":60281,"q":"週末に","a":"on weekends","choices":["on weekends","on business","run away","look around","pass the exam"]},
{"id":60282,"q":"one more","a":"もう1つの","choices":["もう1つの","～の1つ","この近くに","貯金する","賞を受ける"]},
{"id":60283,"q":"もう1つの","a":"one more","choices":["one more","one of ～","near here","save money","receive a prize"]},
{"id":60284,"q":"one of ～","a":"～の1つ","choices":["～の1つ","もう1つの","右手に","向こうに","ちょうど今"]},
{"id":60285,"q":"～の1つ","a":"one of ～","choices":["one of ～","one more","on one's right","over ther","right now"]},
{"id":60286,"q":"over ther","a":"向こうに","choices":["向こうに","この近くに","～を探す","辺りを見回す","週末に"]},
{"id":60287,"q":"向こうに","a":"over ther","choices":["over ther","near here","look for ～","look around","on weekends"]},
{"id":60288,"q":"pass the exam","a":"試験に合格する","choices":["試験に合格する","賞を受ける","仕事で","右手に","逃げ去る"]},
{"id":60289,"q":"試験に合格する","a":"pass the exam","choices":["pass the exam","receive a prize","on business","on one's right","run away"]},
{"id":60290,"q":"pick up ～","a":"～を車で迎えに来る","choices":["～を車で迎えに来る","～に移動する","この近くに","向こうに","ちょうど今"]},
{"id":60291,"q":"～を車で迎えに来る","a":"pick up ～","choices":["pick up ～","move to ～","near here","over ther","right now"]},
{"id":60292,"q":"put on ～","a":"～を着る","choices":["～を着る","賞を受ける","辺りを見回す","週末に","仕事で"]},
{"id":60293,"q":"～を着る","a":"put on ～","choices":["put on ～","receive a prize","look around","on weekends","on business"]},
{"id":60294,"q":"receive a prize","a":"賞を受ける","choices":["賞を受ける","試験に合格する","向こうに","この近くに","急ぐ"]},
{"id":60295,"q":"賞を受ける","a":"receive a prize","choices":["receive a prize","pass the exam","over ther","near here","hurry up"]},
{"id":60296,"q":"right now","a":"ちょうど今","choices":["ちょうど今","週末に","逃げ去る","～のほとんど","仕事で"]},
{"id":60297,"q":"ちょうど今","a":"right now","choices":["right now","on weekends","run away","most of ～","on business"]},
{"id":60298,"q":"run away","a":"逃げ去る","choices":["逃げ去る","急ぐ","辺りを見回す","賞を受ける","もう1つの"]},
{"id":60299,"q":"逃げ去る","a":"run away","choices":["run away","hurry up","look around","receive a prize","one more"]},
{"id":60300,"q":"save money","a":"貯金する","choices":["貯金する","～を探す","この近くに","向こうに","週末に"]},
{"id":60301,"q":"貯金する","a":"save money","choices":["save money","look for ～","near here","over ther","on weekends"]},
{"id":60302,"q":"say hello to ～","a":"～によろしく伝える","choices":["～によろしく伝える","～と握手する","～に叫ぶ","～を捨てる","～を試着する"]},
{"id":60303,"q":"～によろしく伝える","a":"say hello to ～","choices":["say hello to ～","shake hands with ～","shout at ～","throw away ～","try on ～"]},
{"id":60304,"q":"shake hands with ～","a":"～と握手する","choices":["～と握手する","～によろしく伝える","～に参加する","電話で話す","家にいる"]},
{"id":60305,"q":"～と握手する","a":"shake hands with ～","choices":["shake hands with ～","say hello to ～","take part in ～","talk on the phone","stay home"]},
{"id":60306,"q":"shout at ～","a":"～に叫ぶ","choices":["～に叫ぶ","～によろしく伝える","～を脱ぐ","写真を撮る","今朝"]},
{"id":60307,"q":"～に叫ぶ","a":"shout at ～","choices":["shout at ～","say hello to ～","take off ～","take a picture","this morning"]},
{"id":60308,"q":"show A how to do","a":"Aに～のやり方を教える","choices":["Aに～のやり方を教える","Aに～するように言う","電話で話す","家にいる","夜更かしする"]},
{"id":60309,"q":"Aに～のやり方を教える","a":"show A how to do","choices":["show A how to do","tell A how to do","talk on the phone","stay home","stay up late"]},
{"id":60310,"q":"so hungry that ～","a":"とても空腹なので～","choices":["とても空腹なので～","とても忙しいので～できない","何か～なもの","先日","今朝"]},
{"id":60311,"q":"とても空腹なので～","a":"so hungry that ～","choices":["so hungry that ～","too busy to do ～","something ～","the other day","this morning"]},
{"id":60312,"q":"something ～","a":"何か～なもの","choices":["何か～なもの","何か～するもの","そのような～","今朝","先日"]},
{"id":60313,"q":"何か～なもの","a":"something ～","choices":["something ～","something to do","such a ～","this morning","the other day"]},
{"id":60314,"q":"something to do","a":"何か～するもの","choices":["何か～するもの","何か～なもの","～について考える","～へ旅行する","～を試着する"]},
{"id":60315,"q":"何か～するもの","a":"something to do","choices":["something to do","something ～","think about doing","travel to ～","try on ～"]},
{"id":60316,"q":"spend alot of money on ～","a":"多くのお金を～に費やす","choices":["多くのお金を～に費やす","～の世話をする","レッスンを受ける","～に参加する","写真を撮る"]},
{"id":60317,"q":"多くのお金を～に費やす","a":"spend alot of money on ～","choices":["spend alot of money on ～","take care of ～","take lessons","take part in ～","take a picture"]},
{"id":60318,"q":"stay home","a":"家にいる","choices":["家にいる","夜更かしする","先日","電話で話す","～を捨てる"]},
{"id":60319,"q":"家にいる","a":"stay home","choices":["stay home","stay up late","the other day","talk on the phone","throw away ～"]},
{"id":60320,"q":"stay up late","a":"夜更かしする","choices":["夜更かしする","家にいる","今朝","～を試着する","～へ旅行する"]},
{"id":60321,"q":"夜更かしする","a":"stay up late","choices":["stay up late","stay home","this morning","try on ～","travel to ～"]},
{"id":60322,"q":"such a ～","a":"そのような～","choices":["そのような～","何か～なもの","とても空腹なので～","いつもより","先日"]},
{"id":60323,"q":"そのような～","a":"such a ～","choices":["such a ～","something ～","so hungry that ～","than usual","the other day"]},
{"id":60324,"q":"take A to B","a":"AをBに連れていく","choices":["AをBに連れていく","Aに～するように言う","Aに～のやり方を教える","～へ旅行する","～に参加する"]},
{"id":60325,"q":"AをBに連れていく","a":"take A to B","choices":["take A to B","tell A to do","show A how to do","travel to ～","take part in ～"]},
{"id":60326,"q":"take a picture","a":"写真を撮る","choices":["写真を撮る","レッスンを受ける","～を脱ぐ","電話で話す","～を捨てる"]},
{"id":60327,"q":"写真を撮る","a":"take a picture","choices":["take a picture","take lessons","take off ～","talk on the phone","throw away ～"]},
{"id":60328,"q":"take care of ～","a":"～の世話をする","choices":["～の世話をする","～に参加する","～に叫ぶ","～へ旅行する","今朝"]},
{"id":60329,"q":"～の世話をする","a":"take care of ～","choices":["take care of ～","take part in ～","shout at ～","travel to ～","this morning"]},
{"id":60330,"q":"take lessons","a":"レッスンを受ける","choices":["レッスンを受ける","写真を撮る","家にいる","夜更かしする","そのような～"]},
{"id":60331,"q":"レッスンを受ける","a":"take lessons","choices":["take lessons","take a picture","stay home","stay up late","such a ～"]},
{"id":60332,"q":"take off","a":"離陸する","choices":["離陸する","～を脱ぐ","～を試着する","～を捨てる","電話で話す"]},
{"id":60333,"q":"離陸する","a":"take off","choices":["take off","take off ～","try on ～","throw away ～","talk on the phone"]},
{"id":60334,"q":"take off ～","a":"～を脱ぐ","choices":["～を脱ぐ","離陸する","～を試着する","家にいる","先日"]},
{"id":60335,"q":"～を脱ぐ","a":"take off ～","choices":["take off ～","take off","try on ～","stay home","the other day"]},
{"id":60336,"q":"take part in ～","a":"～に参加する","choices":["～に参加する","～の世話をする","AをBに連れていく","～によろしく伝える","写真を撮る"]},
{"id":60337,"q":"～に参加する","a":"take part in ～","choices":["take part in ～","take care of ～","take A to B","say hello to ～","take a picture"]},
{"id":60338,"q":"talk on the phone","a":"電話で話す","choices":["電話で話す","～に叫ぶ","家にいる","今朝","夜更かしする"]},
{"id":60339,"q":"電話で話す","a":"talk on the phone","choices":["talk on the phone","shout at ～","stay home","this morning","stay up late"]},
{"id":60340,"q":"tell A how to do","a":"Aに～のやり方を教える","choices":["Aに～のやり方を教える","Aに～するように言う","AをBに連れていく","そのような～","～を試着する"]},
{"id":60341,"q":"Aに～のやり方を教える","a":"tell A how to do","choices":["tell A how to do","tell A to do","take A to B","such a ～","try on ～"]},
{"id":60342,"q":"tell A to do","a":"Aに～するように言う","choices":["Aに～するように言う","Aに～のやり方を教える","～に参加する","離陸する","写真を撮る"]},
{"id":60343,"q":"Aに～するように言う","a":"tell A to do","choices":["tell A to do","tell A how to do","take part in ～","take off","take a picture"]},
{"id":60344,"q":"than usual","a":"いつもより","choices":["いつもより","先日","今朝","家にいる","夜更かしする"]},
{"id":60345,"q":"いつもより","a":"than usual","choices":["than usual","the other day","this morning","stay home","stay up late"]},
{"id":60346,"q":"the other day","a":"先日","choices":["先日","今朝","いつもより","～を捨てる","～へ旅行する"]},
{"id":60347,"q":"先日","a":"the other day","choices":["the other day","this morning","than usual","throw away ～","travel to ～"]},
{"id":60348,"q":"think about doing","a":"～することについて考える","choices":["～することについて考える","～のことを考える","何か～するもの","～に参加する","～を試着する"]},
{"id":60349,"q":"～することについて考える","a":"think about doing","choices":["think about doing","think of ～","something to do","take part in ～","try on ～"]},
{"id":60350,"q":"think of ～","a":"～のことを考える","choices":["～のことを考える","～することについて考える","何か～なもの","写真を撮る","離陸する"]},
{"id":60351,"q":"～のことを考える","a":"think of ～","choices":["think of ～","think about doing","something ～","take a picture","take off"]},
{"id":60352,"q":"this morning","a":"今朝","choices":["今朝","先日","いつもより","電話で話す","家にいる"]},
{"id":60353,"q":"今朝","a":"this morning","choices":["this morning","the other day","than usual","talk on the phone","stay home"]},
{"id":60354,"q":"throw away ～","a":"～を捨てる","choices":["～を捨てる","～を脱ぐ","～を試着する","離陸する","夜更かしする"]},
{"id":60355,"q":"～を捨てる","a":"throw away ～","choices":["throw away ～","take off ～","try on ～","take off","stay up late"]},
{"id":60356,"q":"too busy to do ～","a":"とても忙しいので～できない","choices":["とても忙しいので～できない","とても空腹なので～","何か～するもの","先日","今朝"]},
{"id":60357,"q":"とても忙しいので～できない","a":"too busy to do ～","choices":["too busy to do ～","so hungry that ～","something to do","the other day","this morning"]},
{"id":60358,"q":"travel to ～","a":"～へ旅行する","choices":["～へ旅行する","～に参加する","～を試着する","家にいる","電話で話す"]},
{"id":60359,"q":"～へ旅行する","a":"travel to ～","choices":["travel to ～","take part in ～","try on ～","stay home","talk on the phone"]},
{"id":60360,"q":"try on ～","a":"～を試着する","choices":["～を試着する","～を脱ぐ","～へ旅行する","～を捨てる","離陸する"]},
{"id":60361,"q":"～を試着する","a":"try on ～","choices":["try on ～","take off ～","travel to ～","throw away ～","take off"]},
{"id":60362,"q":"turn down ～","a":"音量を下げる","choices":["音量を下げる","音量を上げる","～を消す","左に曲がる","起きる"]},
{"id":60363,"q":"音量を下げる","a":"turn down ～","choices":["turn down ～","turn up ～","turn off ～","turn left","wake up"]},
{"id":60364,"q":"turn left","a":"左に曲がる","choices":["左に曲がる","音量を下げる","起きる","うまくいく","～を待つ"]},
{"id":60365,"q":"左に曲がる","a":"turn left","choices":["turn left","turn down ～","wake up","work well","wait for ～"]},
{"id":60366,"q":"turn off ～","a":"～を消す","choices":["～を消す","音量を下げる","音量を上げる","起きる","うまくいく"]},
{"id":60367,"q":"～を消す","a":"turn off ～","choices":["turn off ～","turn down ～","turn up ～","wake up","work well"]},
{"id":60368,"q":"turn up ～","a":"音量を上げる","choices":["音量を上げる","音量を下げる","～を消す","左に曲がる","起きる"]},
{"id":60369,"q":"音量を上げる","a":"turn up ～","choices":["turn up ～","turn down ～","turn off ～","turn left","wake up"]},
{"id":60370,"q":"twice a month","a":"月に2回","choices":["月に2回","～歳","起きる","うまくいく","左に曲がる"]},
{"id":60371,"q":"月に2回","a":"twice a month","choices":["twice a month","～ years old","wake up","work well","turn left"]},
{"id":60372,"q":"visit A in the hospital","a":"入院中のAを見舞う","choices":["入院中のAを見舞う","～を待つ","Aに～してもらいたい","起きる","うまくいく"]},
{"id":60373,"q":"入院中のAを見舞う","a":"visit A in the hospital","choices":["visit A in the hospital","wait for ～","want A to do","wake up","work well"]},
{"id":60374,"q":"wait for ～","a":"～を待つ","choices":["～を待つ","入院中のAを見舞う","～に沿って歩く","左に曲がる","起きる"]},
{"id":60375,"q":"～を待つ","a":"wait for ～","choices":["wait for ～","visit A in the hospital","walk along ～","turn left","wake up"]},
{"id":60376,"q":"wake up","a":"起きる","choices":["起きる","左に曲がる","うまくいく","～を待つ","音量を上げる"]},
{"id":60377,"q":"起きる","a":"wake up","choices":["wake up","turn left","work well","wait for ～","turn up ～"]},
{"id":60378,"q":"walk along ～","a":"～に沿って歩く","choices":["～に沿って歩く","～を待つ","左に曲がる","どこへ～すべきか","いつ～すべきか"]},
{"id":60379,"q":"～に沿って歩く","a":"walk along ～","choices":["walk along ～","wait for ～","turn left","where to do","when to do"]},
{"id":60380,"q":"want A to do","a":"Aに～してもらいたい","choices":["Aに～してもらいたい","～になりたい","何を～すべきか","いつ～すべきか","どこへ～すべきか"]},
{"id":60381,"q":"Aに～してもらいたい","a":"want A to do","choices":["want A to do","want to be","what to do","when to do","where to do"]},
{"id":60382,"q":"want to be","a":"～になりたい","choices":["～になりたい","Aに～してもらいたい","何を～すべきか","起きる","うまくいく"]},
{"id":60383,"q":"～になりたい","a":"want to be","choices":["want to be","want A to do","what to do","wake up","work well"]},
{"id":60384,"q":"what to do","a":"何を～すべきか","choices":["何を～すべきか","いつ～すべきか","どこへ～すべきか","～になりたい","Aに～してもらいたい"]},
{"id":60385,"q":"何を～すべきか","a":"what to do","choices":["what to do","when to do","where to do","want to be","want A to do"]},
{"id":60386,"q":"when to do","a":"いつ～すべきか","choices":["いつ～すべきか","何を～すべきか","どこへ～すべきか","起きる","左に曲がる"]},
{"id":60387,"q":"いつ～すべきか","a":"when to do","choices":["when to do","what to do","where to do","wake up","turn left"]},
{"id":60388,"q":"where to do","a":"どこへ～すべきか","choices":["どこへ～すべきか","何を～すべきか","いつ～すべきか","うまくいく","～を待つ"]},
{"id":60389,"q":"どこへ～すべきか","a":"where to do","choices":["where to do","what to do","when to do","work well","wait for ～"]},
{"id":60390,"q":"work well","a":"うまくいく","choices":["うまくいく","起きる","左に曲がる","音量を上げる","～を消す"]},
{"id":60391,"q":"うまくいく","a":"work well","choices":["work well","wake up","turn left","turn up ～","turn off ～"]},
{"id":60392,"q":"～ years old","a":"～歳","choices":["～歳","月に2回","～になりたい","何を～すべきか","起きる"]},
{"id":60393,"q":"～歳","a":"～ years old","choices":["～ years old","twice a month","want to be","what to do","wake up"]},
]

# 任意でシャッフル関数
def shuffled():
    items = QUESTIONS.copy()
    random.shuffle(items)
    return items




