import random

QUESTIONS = [
{"id":1,"q":"「be（～である）の過去形」はどれ？","a":"was","choices":["was","been","is","being","do"]},
{"id":2,"q":"「be（～である）の過去分詞」はどれ？","a":"been","choices":["was","been","is","being","do"]},
{"id":3,"q":"「私は疲れていた＝I (  ) tired.」(  )に入るのはどれ？","a":"was","choices":["was","been","is","being","do"]},
{"id":4,"q":"「私は疲れていたことがある＝I have (  ) tired.」(  )に入るのはどれ？","a":"been","choices":["was","been","is","being","do"]},
#{"id":3,"q":"「be（～である）の三人称単数現在形」はどれ？","a":"is","choices":["was","been","is","being","do"]},
#{"id":4,"q":"「be（～である）の現在分詞」はどれ？","a":"being","choices":["was","been","is","being","do"]},
{"id":5,"q":"「become（～になる）の過去形」はどれ？","a":"became","choices":["became","become","becomes","becoming","been"]},
{"id":6,"q":"「become（～になる）の過去分詞」はどれ？","a":"become","choices":["became","become","becomes","becoming","been"]},
{"id":7,"q":"「彼女は静かになった＝She (  ) quiet.」(　)に入るのはどれ？","a":"became","choices":["became","become","becomes","becoming","been"]},
{"id":8,"q":"「彼女は静かになってきた＝She has (  ) quiet.」(　)に入るのはどれ？","a":"become","choices":["became","become","becomes","becoming","been"]},
#{"id":7,"q":"「become（～になる）の三人称単数現在形」はどれ？","a":"becomes","choices":["became","become","becomes","becoming","been"]},
#{"id":8,"q":"「become（～になる）の現在分詞」はどれ？","a":"becoming","choices":["became","become","becomes","becoming","been"]},
{"id":9,"q":"「begin（始める）の過去形」はどれ？","a":"began","choices":["began","begun","begins","beginning","become"]},
{"id":10,"q":"「begin（始める）の過去分詞」はどれ？","a":"begun","choices":["began","begun","begins","beginning","become"]},
{"id":11,"q":"「会議は9時に始まった＝The meeting (  ) at 9 a.m.」(  )に入るのはどれ？","a":"began","choices":["began","begun","begins","beginning","become"]},
{"id":12,"q":"「会議はすでに始められている＝The meeting has been (  )」(  )に入るのはどれ？","a":"begun","choices":["began","begun","begins","beginning","become"]},
#{"id":11,"q":"「begin（始める）の三人称単数現在形」はどれ？","a":"begins","choices":["began","begun","begins","beginning","become"]},
#{"id":12,"q":"「begin（始める）の現在分詞」はどれ？","a":"beginning","choices":["began","begun","begins","beginning","become"]},
{"id":13,"q":"「break（壊す）の過去形」はどれ？","a":"broke","choices":["broke","broken","breaks","breaking","begin"]},
{"id":14,"q":"「break（壊す）の過去分詞」はどれ？","a":"broken","choices":["broke","broken","breaks","breaking","begin"]},
{"id":15,"q":"「私は窓を割った＝I (  ) the window.」(  )に入るのはどれ？","a":"broke","choices":["broke","broken","breaks","breaking","begin"]},
{"id":16,"q":"「窓は私によって割られた＝The window was (  ) by me.」(  )に入るのはどれ？","a":"broken","choices":["broke","broken","breaks","breaking","begin"]},
#{"id":15,"q":"「break（壊す）の三人称単数現在形」はどれ？","a":"breaks","choices":["broke","broken","breaks","breaking","begin"]},
#{"id":16,"q":"「break（壊す）の現在分詞」はどれ？","a":"breaking","choices":["broke","broken","breaks","breaking","begin"]},
{"id":17,"q":"「bring（持ってくる）の過去形」はどれ？","a":"brought","choices":["brought","bring","brings","bringing","break"]},
{"id":18,"q":"「bring（持ってくる）の過去分詞」はどれ？","a":"brought","choices":["brought","bring","brings","bringing","break"]},
{"id":19,"q":"「私はそのバッグを持ってきた＝I (  ) the bag.」(  )に入るのはどれ？","a":"brought","choices":["brought","bring","brings","bringing","break"]},
{"id":20,"q":"「そのバッグは私によって持ってこられた＝The bag was (  ) by me.」(  )に入るのはどれ？","a":"brought","choices":["brought","bring","brings","bringing","break"]},
#{"id":19,"q":"「bring（持ってくる）の三人称単数現在形」はどれ？","a":"brings","choices":["brought","bring","brings","bringing","break"]},
#{"id":20,"q":"「bring（持ってくる）の現在分詞」はどれ？","a":"bringing","choices":["brought","bring","brings","bringing","break"]},
{"id":21,"q":"「build（建てる）の過去形」はどれ？","a":"built","choices":["built","build","builds","building","bring"]},
{"id":22,"q":"「build（建てる）の過去分詞」はどれ？","a":"built","choices":["built","build","builds","building","bring"]},
{"id":23,"q":"「彼はその家を建てた＝He (  ) the house.」(  )に入るのはどれ？","a":"built","choices":["built","build","builds","building","bring"]},
{"id":24,"q":"「その家は彼によって建てられた＝The house was (  ) by him.」(  )に入るのはどれ？","a":"built","choices":["built","build","builds","building","bring"]},
#{"id":23,"q":"「build（建てる）の三人称単数現在形」はどれ？","a":"builds","choices":["built","build","builds","building","bring"]},
#{"id":24,"q":"「build（建てる）の現在分詞」はどれ？","a":"building","choices":["built","build","builds","building","bring"]},
{"id":25,"q":"「burn（燃やす）の過去形」はどれ？","a":"burned","choices":["burned","burnt","burns","burning","build"]},
{"id":26,"q":"「burn（燃やす）の過去分詞」はどれ？","a":"burned","choices":["burned","burnt","burns","burning","build"]},
{"id":27,"q":"「トムはその紙を燃やした＝Tom (  ) the paper.」(  )に入るのはどれ？","a":"burned","choices":["burned","burnt","burns","burning","build"]},
{"id":28,"q":"「その紙はトムによって燃やされた＝The paper was (  ) by Tom.」(  )に入るのはどれ？","a":"burned","choices":["burned","burnt","burns","burning","build"]},
#{"id":27,"q":"「burn（燃やす）の三人称単数現在形」はどれ？","a":"burns","choices":["burned","burnt","burns","burning","build"]},
#{"id":28,"q":"「burn（燃やす）の現在分詞」はどれ？","a":"burning","choices":["burned","burnt","burns","burning","build"]},
{"id":29,"q":"「buy（買う）の過去形」はどれ？","a":"bought","choices":["bought","buy","buys","buying","burn"]},
{"id":30,"q":"「buy（買う）の過去分詞」はどれ？","a":"bought","choices":["bought","buy","buys","buying","burn"]},
{"id":31,"q":"「安田はその本を買った＝Yasuda (  ) the book.」(  )に入るのはどれ？","a":"bought","choices":["bought","buy","buys","buying","burn"]},
{"id":32,"q":"「安田によって買われた本＝The book was (  ) by Yasuda.」(  )に入るのはどれ？","a":"bought","choices":["bought","buy","buys","buying","burn"]},
#{"id":31,"q":"「buy（買う）の三人称単数現在形」はどれ？","a":"buys","choices":["bought","buy","buys","buying","burn"]},
#{"id":32,"q":"「buy（買う）の現在分詞」はどれ？","a":"buying","choices":["bought","buy","buys","buying","burn"]},
{"id":33,"q":"「catch（捕まえる）の過去形」はどれ？","a":"caught","choices":["caught","catch","catches","catching","buy"]},
{"id":34,"q":"「catch（捕まえる）の過去分詞」はどれ？","a":"caught","choices":["caught","catch","catches","catching","buy"]},
{"id":35,"q":"「私はそのボールを捕まえた＝I (  ) the ball.」(  )に入るのはどれ？","a":"caught","choices":["caught","catch","catches","catching","buy"]},
{"id":36,"q":"「そのボールは捕まえられている＝The ball is (  ).」(  )に入るのはどれ？","a":"caught","choices":["caught","catch","catches","catching","buy"]},
#{"id":35,"q":"「catch（捕まえる）の三人称単数現在形」はどれ？","a":"catches","choices":["caught","catch","catches","catching","buy"]},
#{"id":36,"q":"「catch（捕まえる）の現在分詞」はどれ？","a":"catching","choices":["caught","catch","catches","catching","buy"]},
{"id":37,"q":"「choose（選ぶ）の過去形」はどれ？","a":"chose","choices":["chose","chosen","chooses","choosing","catch"]},
{"id":38,"q":"「choose（選ぶ）の過去分詞」はどれ？","a":"chosen","choices":["chose","chosen","chooses","choosing","catch"]},
{"id":39,"q":"「彼はその色を選んだ＝He (  ) the color.」(  )に入るのはどれ？","a":"chose","choices":["chose","chosen","chooses","choosing","catch"]},
{"id":40,"q":"「彼によって選ばれた色＝The color was (  ) by him.」(  )に入るのはどれ？","a":"chosen","choices":["chose","chosen","chooses","choosing","catch"]},
#{"id":39,"q":"「choose（選ぶ）の三人称単数現在形」はどれ？","a":"chooses","choices":["chose","chosen","chooses","choosing","catch"]},
#{"id":40,"q":"「choose（選ぶ）の現在分詞」はどれ？","a":"choosing","choices":["chose","chosen","chooses","choosing","catch"]},
{"id":41,"q":"「come（来る）の過去形」はどれ？","a":"came","choices":["came","come","comes","coming","choose"]},
{"id":42,"q":"「come（来る）の過去分詞」はどれ？","a":"come","choices":["came","come","comes","coming","choose"]},
{"id":43,"q":"「彼はここに来た＝He (  ) here.」(  )に入るのはどれ？","a":"came","choices":["came","come","comes","coming","choose"]},
{"id":44,"q":"「彼はすでに来ている＝He has (  ) here.」(  )に入るのはどれ？","a":"come","choices":["came","come","comes","coming","choose"]},
#{"id":43,"q":"「come（来る）の三人称単数現在形」はどれ？","a":"comes","choices":["came","come","comes","coming","choose"]},
#{"id":44,"q":"「come（来る）の現在分詞」はどれ？","a":"coming","choices":["came","come","comes","coming","choose"]},
{"id":45,"q":"「cut（切る）の過去形」はどれ？","a":"cut","choices":["cut","cuts","cutting","cut","come"]},
{"id":46,"q":"「cut（切る）の過去分詞」はどれ？","a":"cut","choices":["cut","cuts","cutting","cut","come"]},
{"id":47,"q":"「彼は紙を切った＝He (  ) the paper.」(  )に入るのはどれ？","a":"cut","choices":["cut","cuts","cutting","cutted","draw"]},
{"id":48,"q":"「その紙は切られている＝The paper is (  ).」(  )に入るのはどれ？","a":"cut","choices":["cut","cuts","cutting","cutted","draw"]},
#{"id":47,"q":"「cut（切る）の三人称単数現在形」はどれ？","a":"cuts","choices":["cut","cuts","cutting","cut","come"]},
#{"id":48,"q":"「cut（切る）の現在分詞」はどれ？","a":"cutting","choices":["cut","cuts","cutting","cut","come"]},
{"id":49,"q":"「do（する）の過去形」はどれ？","a":"did","choices":["did","done","does","doing","dog"]},
{"id":50,"q":"「do（する）の過去分詞」はどれ？","a":"done","choices":["did","done","does","doing","dog"]},
{"id":51,"q":"「彼女は宿題をした＝She (  ) her homework.」(  )に入るのはどれ？","a":"did","choices":["did","do","does","doing","draw"]},
{"id":52,"q":"「宿題は終わっている＝The homework is (  ).」(  )に入るのはどれ？","a":"done","choices":["done","did","does","doing","draw"]},
#{"id":51,"q":"「do（する）の三人称単数現在形」はどれ？","a":"does","choices":["did","done","does","doing","dog"]},
#{"id":52,"q":"「do（する）の現在分詞」はどれ？","a":"doing","choices":["did","done","does","doing","dog"]},
{"id":53,"q":"「draw（描く）の過去形」はどれ？","a":"drew","choices":["drew","drawn","draws","drawing","do"]},
{"id":54,"q":"「draw（描く）の過去分詞」はどれ？","a":"drawn","choices":["drew","drawn","draws","drawing","do"]},
{"id":55,"q":"「彼は絵を描いた＝He (  ) a picture.」(  )に入るのはどれ？","a":"drew","choices":["drew","draw","draws","drawing","drink"]},
{"id":56,"q":"「描かれた絵＝The (  ) picture is beautiful.」(  )に入るのはどれ？","a":"drawn","choices":["drawn","drew","draws","drawing","drink"]},
#{"id":55,"q":"「draw（描く）の三人称単数現在形」はどれ？","a":"draws","choices":["drew","drawn","draws","drawing","do"]},
#{"id":56,"q":"「draw（描く）の現在分詞」はどれ？","a":"drawing","choices":["drew","drawn","draws","drawing","do"]},
{"id":57,"q":"「drink（飲む）の過去形」はどれ？","a":"drank","choices":["drank","drunk","drinks","drinking","draw"]},
{"id":58,"q":"「drink（飲む）の過去分詞」はどれ？","a":"drunk","choices":["drank","drunk","drinks","drinking","draw"]},
{"id":59,"q":"「彼女は水を飲んだ＝She (  ) water.」(  )に入るのはどれ？","a":"drank","choices":["drank","drink","drinks","drinking","drive"]},
{"id":60,"q":"「水はもう飲まれている＝The water has been (  ).」(  )に入るのはどれ？","a":"drunk","choices":["drunk","drank","drinks","drinking","drive"]},
#{"id":59,"q":"「drink（飲む）の三人称単数現在形」はどれ？","a":"drinks","choices":["drank","drunk","drinks","drinking","draw"]},
#{"id":60,"q":"「drink（飲む）の現在分詞」はどれ？","a":"drinking","choices":["drank","drunk","drinks","drinking","draw"]},
{"id":61,"q":"「drive（運転する）の過去形」はどれ？","a":"drove","choices":["drove","driven","drives","driving","drink"]},
{"id":62,"q":"「drive（運転する）の過去分詞」はどれ？","a":"driven","choices":["drove","driven","drives","driving","drink"]},
{"id":63,"q":"「彼は車を運転した＝He (  ) a car.」(  )に入るのはどれ？","a":"drove","choices":["drove","drive","drives","driving","eat"]},
{"id":64,"q":"「その車は彼によって運転された＝The car was (  ) by him.」(  )に入るのはどれ？","a":"driven","choices":["driven","drove","drives","driving","eat"]},
#{"id":63,"q":"「drive（運転する）の三人称単数現在形」はどれ？","a":"drives","choices":["drove","driven","drives","driving","drink"]},
#{"id":64,"q":"「drive（運転する）の現在分詞」はどれ？","a":"driving","choices":["drove","driven","drives","driving","drink"]},
{"id":65,"q":"「eat（食べる）の過去形」はどれ？","a":"ate","choices":["ate","eaten","eats","eating","east"]},
{"id":66,"q":"「eat（食べる）の過去分詞」はどれ？","a":"eaten","choices":["ate","eaten","eats","eating","east"]},
{"id":67,"q":"「彼女は昼食を食べた＝She (  ) lunch.」(  )に入るのはどれ？","a":"ate","choices":["ate","eat","eats","eating","fall"]},
{"id":68,"q":"「昼食はすでに食べ終わっている＝The lunch is already (  ).」(  )に入るのはどれ？","a":"eaten","choices":["eaten","ate","eats","eating","fall"]},
#{"id":67,"q":"「eat（食べる）の三人称単数現在形」はどれ？","a":"eats","choices":["ate","eaten","eats","eating","east"]},
#{"id":68,"q":"「eat（食べる）の現在分詞」はどれ？","a":"eating","choices":["ate","eaten","eats","eating","east"]},
{"id":69,"q":"「fall（落ちる）の過去形」はどれ？","a":"fell","choices":["fell","fallen","falls","falling","fail"]},
{"id":70,"q":"「fall（落ちる）の過去分詞」はどれ？","a":"fallen","choices":["fell","fallen","falls","falling","fail"]},
{"id":71,"q":"「彼は転んだ＝He (  ) down.」(  )に入るのはどれ？","a":"fell","choices":["fell","fall","falls","falling","feel"]},
{"id":72,"q":"「倒れた木＝The (  ) tree blocked the road.」(  )に入るのはどれ？","a":"fallen","choices":["fallen","fell","falls","falling","feel"]},
#{"id":71,"q":"「fall（落ちる）の三人称単数現在形」はどれ？","a":"falls","choices":["fell","fallen","falls","falling","fail"]},
#{"id":72,"q":"「fall（落ちる）の現在分詞」はどれ？","a":"falling","choices":["fell","fallen","falls","falling","fail"]},
{"id":73,"q":"「feel（感じる）の過去形」はどれ？","a":"felt","choices":["felt","feels","feeling","felt","fall"]},
{"id":74,"q":"「feel（感じる）の過去分詞」はどれ？","a":"felt","choices":["felt","feels","feeling","felt","fall"]},
{"id":75,"q":"「彼女は悲しみを感じた＝She (  ) sad.」(  )に入るのはどれ？","a":"felt","choices":["felt","feel","feels","feeling","fall"]},
{"id":76,"q":"「彼は疲れている＝He looks (  ).」(  )に入るのはどれ？","a":"felt","choices":["felt","feel","feels","feeling","fall"]},
#{"id":75,"q":"「feel（感じる）の三人称単数現在形」はどれ？","a":"feels","choices":["felt","feels","feeling","felt","fall"]},
#{"id":76,"q":"「feel（感じる）の現在分詞」はどれ？","a":"feeling","choices":["felt","feels","feeling","felt","fall"]},
{"id":77,"q":"「fight（戦う）の過去形」はどれ？","a":"fought","choices":["fought","fight","fights","fighting","feel"]},
{"id":78,"q":"「fight（戦う）の過去分詞」はどれ？","a":"fought","choices":["fought","fight","fights","fighting","feel"]},
{"id":79,"q":"「彼はその試合で戦った＝He (  ) in the match.」(  )に入るのはどれ？","a":"fought","choices":["fought","fight","fights","fighting","feel"]},
{"id":80,"q":"「その戦いはすでに終わっている＝The fight is already (  ).」(  )に入るのはどれ？","a":"fought","choices":["fought","fight","fights","fighting","feel"]},
#{"id":79,"q":"「fight（戦う）の三人称単数現在形」はどれ？","a":"fights","choices":["fought","fight","fights","fighting","feel"]},
#{"id":80,"q":"「fight（戦う）の現在分詞」はどれ？","a":"fighting","choices":["fought","fight","fights","fighting","feel"]},
{"id":81,"q":"「find（見つける）の過去形」はどれ？","a":"found","choices":["found","find","finds","finding","fight"]},
{"id":82,"q":"「find（見つける）の過去分詞」はどれ？","a":"found","choices":["found","find","finds","finding","fight"]},
{"id":83,"q":"「彼は答えを見つけた＝He (  ) the answer.」(  )に入るのはどれ？","a":"found","choices":["found","find","finds","finding","feel"]},
{"id":84,"q":"「見つかった答え＝The (  ) answer was correct.」(  )に入るのはどれ？","a":"found","choices":["found","find","finds","finding","feel"]},
#{"id":83,"q":"「find（見つける）の三人称単数現在形」はどれ？","a":"finds","choices":["found","find","finds","finding","fight"]},
#{"id":84,"q":"「find（見つける）の現在分詞」はどれ？","a":"finding","choices":["found","find","finds","finding","fight"]},
{"id":85,"q":"「fly（飛ぶ）の過去形」はどれ？","a":"flew","choices":["flew","flown","flies","flying","find"]},
{"id":86,"q":"「fly（飛ぶ）の過去分詞」はどれ？","a":"flown","choices":["flew","flown","flies","flying","find"]},
{"id":87,"q":"「彼女は鳥を飛ばした＝She (  ) in the sky.」(  )に入るのはどれ？","a":"flew","choices":["flew","fly","flies","flying","fall"]},
{"id":88,"q":"「飛んだ鳥＝The (  ) bird was beautiful.」(  )に入るのはどれ？","a":"flown","choices":["flown","flew","flies","flying","fall"]},
#{"id":87,"q":"「fly（飛ぶ）の三人称単数現在形」はどれ？","a":"flies","choices":["flew","flown","flies","flying","find"]},
#{"id":88,"q":"「fly（飛ぶ）の現在分詞」はどれ？","a":"flying","choices":["flew","flown","flies","flying","find"]},
{"id":89,"q":"「forget（忘れる）の過去形」はどれ？","a":"forgot","choices":["forgot","forgotten","forgets","forgetting","fly"]},
{"id":90,"q":"「forget（忘れる）の過去分詞」はどれ？","a":"forgotten","choices":["forgot","forgotten","forgets","forgetting","fly"]},
{"id":91,"q":"「彼は約束を忘れた＝He (  ) the promise.」(  )に入るのはどれ？","a":"forgot","choices":["forgot","forget","forgets","forgetting","forgive"]},
{"id":92,"q":"「忘れられた約束＝The (  ) promise caused trouble.」(  )に入るのはどれ？","a":"forgotten","choices":["forgotten","forgot","forgets","forgetting","forgive"]},
#{"id":91,"q":"「forget（忘れる）の三人称単数現在形」はどれ？","a":"forgets","choices":["forgot","forgotten","forgets","forgetting","fly"]},
#{"id":92,"q":"「forget（忘れる）の現在分詞」はどれ？","a":"forgetting","choices":["forgot","forgotten","forgets","forgetting","fly"]},
{"id":93,"q":"「get（得る）の過去形」はどれ？","a":"got","choices":["got","gotten","gets","getting","great"]},
{"id":94,"q":"「get（得る）の過去分詞」はどれ？","a":"got","choices":["got","gotten","gets","getting","great"]},
{"id":95,"q":"「彼女はプレゼントをもらった＝She (  ) a gift.」(  )に入るのはどれ？","a":"got","choices":["got","get","gets","getting","give"]},
{"id":96,"q":"「プレゼントはもう手に入っている＝The gift is already (  ).」(  )に入るのはどれ？","a":"gotten","choices":["gotten","got","gets","getting","give"]},
#{"id":95,"q":"「get（得る）の三人称単数現在形」はどれ？","a":"gets","choices":["got","gotten","gets","getting","great"]},
#{"id":96,"q":"「get（得る）の現在分詞」はどれ？","a":"getting","choices":["got","gotten","gets","getting","great"]},
{"id":97,"q":"「give（与える）の過去形」はどれ？","a":"gave","choices":["gave","given","gives","giving","get"]},
{"id":98,"q":"「give（与える）の過去分詞」はどれ？","a":"given","choices":["gave","given","gives","giving","get"]},
{"id":99,"q":"「彼は彼女に物を与えた＝He (  ) her a book.」(  )に入るのはどれ？","a":"gave","choices":["gave","give","gives","giving","get"]},
{"id":100,"q":"「彼女は本を与えられた＝She was (  ) a book.」(  )に入るのはどれ？","a":"given","choices":["given","gave","gives","giving","get"]},
#{"id":99,"q":"「give（与える）の三人称単数現在形」はどれ？","a":"gives","choices":["gave","given","gives","giving","get"]},
#{"id":100,"q":"「give（与える）の現在分詞」はどれ？","a":"giving","choices":["gave","given","gives","giving","get"]},
{"id":101,"q":"「go（行く）の過去形」はどれ？","a":"went","choices":["went","gone","goes","going","give"]},
{"id":102,"q":"「go（行く）の過去分詞」はどれ？","a":"gone","choices":["went","gone","goes","going","give"]},
{"id":103,"q":"「彼は家に行った＝He (  ) home.」(  )に入るのはどれ？","a":"went","choices":["went","gone","goes","going","give"]},
{"id":104,"q":"「彼はもう行ってしまっている＝He has (  ).」(  )に入るのはどれ？","a":"gone","choices":["went","gone","goes","going","give"]},
#{"id":103,"q":"「go（行く）の三人称単数現在形」はどれ？","a":"goes","choices":["went","gone","goes","going","give"]},
#{"id":104,"q":"「go（行く）の現在分詞」はどれ？","a":"going","choices":["went","gone","goes","going","give"]},
{"id":105,"q":"「grow（成長する）の過去形」はどれ？","a":"grew","choices":["grew","grown","grows","growing","great"]},
{"id":106,"q":"「grow（成長する）の過去分詞」はどれ？","a":"grown","choices":["grew","grown","grows","growing","great"]},
{"id":107,"q":"「その町は大きく成長した＝The town (  ) quickly.」(  )に入るのはどれ？","a":"grew","choices":["grew","grown","grows","growing","great"]},
{"id":108,"q":"「成長した木＝The (  ) tree.」(  )に入るのはどれ？","a":"grown","choices":["grew","grown","grows","growing","great"]},
#{"id":107,"q":"「grow（成長する）の三人称単数現在形」はどれ？","a":"grows","choices":["grew","grown","grows","growing","great"]},
#{"id":108,"q":"「grow（成長する）の現在分詞」はどれ？","a":"growing","choices":["grew","grown","grows","growing","great"]},
{"id":109,"q":"「have（持つ）の過去形」はどれ？","a":"had","choices":["had","has","having","had","head"]},
{"id":110,"q":"「have（持つ）の過去分詞」はどれ？","a":"had","choices":["had","has","having","had","head"]},
{"id":111,"q":"「彼は車を持っていた＝He (  ) a car.」(  )に入るのはどれ？","a":"had","choices":["had","have","has","having","head"]},
{"id":112,"q":"「彼はすでに十分な時間を持っている＝He has (  ) enough time.」(  )に入るのはどれ？","a":"had","choices":["had","have","has","having","head"]},
#{"id":111,"q":"「have（持つ）の三人称単数現在形」はどれ？","a":"has","choices":["had","has","having","had","head"]},
#{"id":112,"q":"「have（持つ）の現在分詞」はどれ？","a":"having","choices":["had","has","having","had","head"]},
{"id":113,"q":"「hear（聞く）の過去形」はどれ？","a":"heard","choices":["heard","hear","hears","hearing","hair"]},
{"id":114,"q":"「hear（聞く）の過去分詞」はどれ？","a":"heard","choices":["heard","hear","hears","hearing","hair"]},
{"id":115,"q":"「彼はその音を聞いた＝He (  ) the sound.」(  )に入るのはどれ？","a":"heard","choices":["heard","hear","hears","hearing","heart"]},
{"id":116,"q":"「彼はその音を聞いたことがある＝He has (  ) the sound.」(  )に入るのはどれ？","a":"heard","choices":["heard","hear","hears","hearing","heart"]},
#{"id":115,"q":"「hear（聞く）の三人称単数現在形」はどれ？","a":"hears","choices":["heard","hear","hears","hearing","hair"]},
#{"id":116,"q":"「hear（聞く）の現在分詞」はどれ？","a":"hearing","choices":["heard","hear","hears","hearing","hair"]},
{"id":117,"q":"「hit（打つ）の過去形」はどれ？","a":"hit","choices":["hit","hits","hitting","hit","hair"]},
{"id":118,"q":"「hit（打つ）の過去分詞」はどれ？","a":"hit","choices":["hit","hits","hitting","hit","hair"]},
{"id":119,"q":"「彼はボールを打った＝He (  ) the ball.」(  )に入るのはどれ？","a":"hit","choices":["hit","hits","hitting","hitten","hat"]},
{"id":120,"q":"「ボールは強く打たれている＝The ball is (  ).」(  )に入るのはどれ？","a":"hit","choices":["hit","hits","hitting","hitten","hat"]},
#{"id":119,"q":"「hit（打つ）の三人称単数現在形」はどれ？","a":"hits","choices":["hit","hits","hitting","hit","hair"]},
#{"id":120,"q":"「hit（打つ）の現在分詞」はどれ？","a":"hitting","choices":["hit","hits","hitting","hit","hair"]},
{"id":121,"q":"「hold（持つ）の過去形」はどれ？","a":"held","choices":["held","hold","holds","holding","home"]},
{"id":122,"q":"「hold（持つ）の過去分詞」はどれ？","a":"held","choices":["held","hold","holds","holding","home"]},
{"id":123,"q":"「彼は重い箱を持っていた＝He (  ) the heavy box.」(  )に入るのはどれ？","a":"held","choices":["held","hold","holds","holding","helmet"]},
{"id":124,"q":"「彼はその箱をずっと持っている＝He has (  ) the box for a long time.」(  )に入るのはどれ？","a":"held","choices":["held","hold","holds","holding","helmet"]},
#{"id":123,"q":"「hold（持つ）の三人称単数現在形」はどれ？","a":"holds","choices":["held","hold","holds","holding","home"]},
#{"id":124,"q":"「hold（持つ）の現在分詞」はどれ？","a":"holding","choices":["held","hold","holds","holding","home"]},
{"id":125,"q":"「hurt（傷つける）の過去形」はどれ？","a":"hurt","choices":["hurt","hurts","hurting","hurt","hold"]},
{"id":126,"q":"「hurt（傷つける）の過去分詞」はどれ？","a":"hurt","choices":["hurt","hurts","hurting","hurt","hold"]},
{"id":127,"q":"「彼は足をけがした＝He (  ) his leg.」(  )に入るのはどれ？","a":"hurt","choices":["hurt","hurt","hurts","hurting","heart"]},
{"id":128,"q":"「彼の足はけがをしている＝His leg is (  ).」(  )に入るのはどれ？","a":"hurt","choices":["hurt","hurt","hurts","hurting","heart"]},
#{"id":127,"q":"「hurt（傷つける）の三人称単数現在形」はどれ？","a":"hurts","choices":["hurt","hurts","hurting","hurt","hold"]},
#{"id":128,"q":"「hurt（傷つける）の現在分詞」はどれ？","a":"hurting","choices":["hurt","hurts","hurting","hurt","hold"]},
{"id":129,"q":"「keep（保つ）の過去形」はどれ？","a":"kept","choices":["kept","keep","keeps","keeping","key"]},
{"id":130,"q":"「keep（保つ）の過去分詞」はどれ？","a":"kept","choices":["kept","keep","keeps","keeping","key"]},
{"id":131,"q":"「彼は約束を守った＝He (  ) his promise.」(  )に入るのはどれ？","a":"kept","choices":["kept","keep","keeps","keeping","key"]},
{"id":132,"q":"「彼はその約束を守り続けている＝He has (  ) his promise.」(  )に入るのはどれ？","a":"kept","choices":["kept","keep","keeps","keeping","key"]},
#{"id":131,"q":"「keep（保つ）の三人称単数現在形」はどれ？","a":"keeps","choices":["kept","keep","keeps","keeping","key"]},
#{"id":132,"q":"「keep（保つ）の現在分詞」はどれ？","a":"keeping","choices":["kept","keep","keeps","keeping","key"]},
{"id":133,"q":"「know（知っている）の過去形」はどれ？","a":"knew","choices":["knew","known","knows","knowing","knife"]},
{"id":134,"q":"「know（知っている）の過去分詞」はどれ？","a":"known","choices":["knew","known","knows","knowing","knife"]},
{"id":135,"q":"「彼はその答えを知っていた＝He (  ) the answer.」(  )に入るのはどれ？","a":"knew","choices":["knew","known","knows","knowing","knife"]},
{"id":136,"q":"「彼は長い間その事実を知っている＝He has (  ) the fact for a long time.」(  )に入るのはどれ？","a":"known","choices":["knew","known","knows","knowing","knife"]},
#{"id":135,"q":"「know（知っている）の三人称単数現在形」はどれ？","a":"knows","choices":["knew","known","knows","knowing","knife"]},
#{"id":136,"q":"「know（知っている）の現在分詞」はどれ？","a":"knowing","choices":["knew","known","knows","knowing","knife"]},
{"id":137,"q":"「lead（導く）の過去形」はどれ？","a":"led","choices":["led","lead","leads","leading","load"]},
{"id":138,"q":"「lead（導く）の過去分詞」はどれ？","a":"led","choices":["led","lead","leads","leading","load"]},
{"id":139,"q":"「彼女はチームを率いた＝She (  ) the team.」(  )に入るのはどれ？","a":"led","choices":["led","lead","leads","leading","load"]},
{"id":140,"q":"「彼女は何度もチームを率いてきた＝She has (  ) the team many times.」(  )に入るのはどれ？","a":"led","choices":["led","lead","leads","leading","load"]},
#{"id":139,"q":"「lead（導く）の三人称単数現在形」はどれ？","a":"leads","choices":["led","lead","leads","leading","load"]},
#{"id":140,"q":"「lead（導く）の現在分詞」はどれ？","a":"leading","choices":["led","lead","leads","leading","load"]},
{"id":141,"q":"「leave（去る）の過去形」はどれ？","a":"left","choices":["left","leave","leaves","leaving","lead"]},
{"id":142,"q":"「leave（去る）の過去分詞」はどれ？","a":"left","choices":["left","leave","leaves","leaving","lead"]},
#{"id":143,"q":"「leave（去る）の三人称単数現在形」はどれ？","a":"leaves","choices":["left","leave","leaves","leaving","lead"]},
#{"id":144,"q":"「leave（去る）の現在分詞」はどれ？","a":"leaving","choices":["left","leave","leaves","leaving","lead"]},
{"id":145,"q":"「lend（貸す）の過去形」はどれ？","a":"lent","choices":["lent","lend","lends","lending","leave"]},
{"id":146,"q":"「lend（貸す）の過去分詞」はどれ？","a":"lent","choices":["lent","lend","lends","lending","leave"]},
{"id":143,"q":"「彼は昨日早く家を出た＝He (  ) home early yesterday.」(  )に入るのはどれ？","a":"left","choices":["left","leave","leaves","leaving","lead"]},
{"id":144,"q":"「彼はすでに家を出ている＝He has already (  ) home.」(  )に入るのはどれ？","a":"left","choices":["left","leave","leaves","leaving","lead"]}
#{"id":147,"q":"「lend（貸す）の三人称単数現在形」はどれ？","a":"lends","choices":["lent","lend","lends","lending","leave"]},
#{"id":148,"q":"「lend（貸す）の現在分詞」はどれ？","a":"lending","choices":["lent","lend","lends","lending","leave"]},
{"id":149,"q":"「lose（失う）の過去形」はどれ？","a":"lost","choices":["lost","lose","loses","losing","look"]},
{"id":150,"q":"「lose（失う）の過去分詞」はどれ？","a":"lost","choices":["lost","lose","loses","losing","look"]},
{"id":151,"q":"「彼は鍵を失くした＝He (  ) his key.」(  )に入るのはどれ？","a":"lost","choices":["lost","lose","loses","losing","look"]},
{"id":152,"q":"「彼は何度も鍵を失くしてきた＝He has (  ) his key many times.」(  )に入るのはどれ？","a":"lost","choices":["lost","lose","loses","losing","look"]},
#{"id":151,"q":"「lose（失う）の三人称単数現在形」はどれ？","a":"loses","choices":["lost","lose","loses","losing","look"]},
#{"id":152,"q":"「lose（失う）の現在分詞」はどれ？","a":"losing","choices":["lost","lose","loses","losing","look"]},
{"id":153,"q":"「make（作る）の過去形」はどれ？","a":"made","choices":["made","make","makes","making","master"]},
{"id":154,"q":"「make（作る）の過去分詞」はどれ？","a":"made","choices":["made","make","makes","making","master"]},
{"id":155,"q":"「彼女はケーキを作った＝She (  ) a cake.」(  )に入るのはどれ？","a":"made","choices":["made","make","makes","making","master"]},
{"id":156,"q":"「彼女はケーキを作ったことがある＝She has (  ) a cake before.」(  )に入るのはどれ？","a":"made","choices":["made","make","makes","making","master"]},
#{"id":155,"q":"「make（作る）の三人称単数現在形」はどれ？","a":"makes","choices":["made","make","makes","making","master"]},
#{"id":156,"q":"「make（作る）の現在分詞」はどれ？","a":"making","choices":["made","make","makes","making","master"]},
{"id":157,"q":"「mean（意味する）の過去形」はどれ？","a":"meant","choices":["meant","mean","means","meaning","meet"]},
{"id":158,"q":"「mean（意味する）の過去分詞」はどれ？","a":"meant","choices":["meant","mean","means","meaning","meet"]},
{"id":159,"q":"「彼の言葉はそれを意味していた＝His words (  ) that.」(  )に入るのはどれ？","a":"meant","choices":["meant","mean","means","meaning","meet"]},
{"id":160,"q":"「その言葉は大切なことを意味してきた＝The word has always (  ) something important.」(  )に入るのはどれ？","a":"meant","choices":["meant","mean","means","meaning","meet"]}
#{"id":159,"q":"「mean（意味する）の三人称単数現在形」はどれ？","a":"means","choices":["meant","mean","means","meaning","meet"]},
#{"id":160,"q":"「mean（意味する）の現在分詞」はどれ？","a":"meaning","choices":["meant","mean","means","meaning","meet"]},
{"id":161,"q":"「meet（会う）の過去形」はどれ？","a":"met","choices":["met","meet","meets","meeting","mean"]},
{"id":162,"q":"「meet（会う）の過去分詞」はどれ？","a":"met","choices":["met","meet","meets","meeting","mean"]},
{"id":163,"q":"「彼は昨日友だちに会った＝He (  ) his friend yesterday.」","a":"met","choices":["met","meet","meets","meeting","mean"]},
{"id":164,"q":"「彼は何度も彼女に会ってきた＝He has (  ) her many times.」","a":"met","choices":["met","meet","meets","meeting","mean"]},
#{"id":163,"q":"「meet（会う）の三人称単数現在形」はどれ？","a":"meets","choices":["met","meet","meets","meeting","mean"]},
#{"id":164,"q":"「meet（会う）の現在分詞」はどれ？","a":"meeting","choices":["met","meet","meets","meeting","mean"]},
{"id":165,"q":"「put（置く）の過去形」はどれ？","a":"put","choices":["put","puts","putting","put","pot"]},
{"id":166,"q":"「put（置く）の過去分詞」はどれ？","a":"put","choices":["put","puts","putting","put","pot"]},
{"id":167,"q":"「彼は本を机に置いた＝He (  ) the book on the desk.」","a":"put","choices":["put","puts","putting","pot","push"]},
{"id":168,"q":"「本はすでに机に置かれている＝The book has been (  ) on the desk.」","a":"put","choices":["put","puts","putting","pot","push"]},
#{"id":167,"q":"「put（置く）の三人称単数現在形」はどれ？","a":"puts","choices":["put","puts","putting","put","pot"]},
#{"id":168,"q":"「put（置く）の現在分詞」はどれ？","a":"putting","choices":["put","puts","putting","put","pot"]},
{"id":169,"q":"「quit（やめる）の過去形」はどれ？","a":"quit","choices":["quit","quits","quitting","quit","question"]},
{"id":170,"q":"「quit（やめる）の過去分詞」はどれ？","a":"quit","choices":["quit","quits","quitting","quit","question"]},
{"id":171,"q":"「彼は仕事をやめた＝He (  ) his job.」","a":"quit","choices":["quit","quits","quitting","quiet","question"]},
{"id":172,"q":"「彼はその仕事をやめている＝He has (  ) the job.」","a":"quit","choices":["quit","quits","quitting","quiet","question"]},
#{"id":171,"q":"「quit（やめる）の三人称単数現在形」はどれ？","a":"quits","choices":["quit","quits","quitting","quit","question"]},
#{"id":172,"q":"「quit（やめる）の現在分詞」はどれ？","a":"quitting","choices":["quit","quits","quitting","quit","question"]},
{"id":173,"q":"「read（読む）の過去形」はどれ？","a":"read","choices":["read","reads","reading","read","red"]},
{"id":174,"q":"「read（読む）の過去分詞」はどれ？","a":"read","choices":["read","reads","reading","read","red"]},
{"id":175,"q":"「彼女はその本を読んだ＝She (  ) the book.」","a":"read","choices":["read","reads","reading","red","ride"]},
{"id":176,"q":"「彼女はその本を読んだことがある＝She has (  ) the book.」","a":"read","choices":["read","reads","reading","red","ride"]}
#{"id":175,"q":"「read（読む）の三人称単数現在形」はどれ？","a":"reads","choices":["read","reads","reading","read","red"]},
#{"id":176,"q":"「read（読む）の現在分詞」はどれ？","a":"reading","choices":["read","reads","reading","read","red"]},
{"id":177,"q":"「ride（乗る）の過去形」はどれ？","a":"rode","choices":["rode","ridden","rides","riding","rider"]},
{"id":178,"q":"「ride（乗る）の過去分詞」はどれ？","a":"ridden","choices":["rode","ridden","rides","riding","rider"]},
{"id":179,"q":"「彼は馬に乗った＝He (  ) a horse.」","a":"rode","choices":["rode","ridden","rides","riding","road"]},
{"id":180,"q":"「彼はその馬に乗ったことがある＝He has (  ) the horse.」","a":"ridden","choices":["rode","ridden","rides","riding","road"]},
#{"id":179,"q":"「ride（乗る）の三人称単数現在形」はどれ？","a":"rides","choices":["rode","ridden","rides","riding","rider"]},
#{"id":180,"q":"「ride（乗る）の現在分詞」はどれ？","a":"riding","choices":["rode","ridden","rides","riding","rider"]},
{"id":181,"q":"「rise（上がる）の過去形」はどれ？","a":"rose","choices":["rose","risen","rises","rising","ride"]},
{"id":182,"q":"「rise（上がる）の過去分詞」はどれ？","a":"risen","choices":["rose","risen","rises","rising","ride"]},
{"id":183,"q":"「太陽は昇った＝The sun (  ).」","a":"rose","choices":["rose","risen","rises","rising","ride"]},
{"id":184,"q":"「太陽はすでに昇っている＝The sun has (  ).」","a":"risen","choices":["rose","risen","rises","rising","ride"]},
#{"id":183,"q":"「rise（上がる）の三人称単数現在形」はどれ？","a":"rises","choices":["rose","risen","rises","rising","ride"]},
#{"id":184,"q":"「rise（上がる）の現在分詞」はどれ？","a":"rising","choices":["rose","risen","rises","rising","ride"]},
{"id":185,"q":"「run（走る）の過去形」はどれ？","a":"ran","choices":["ran","run","runs","running","read"]},
{"id":186,"q":"「run（走る）の過去分詞」はどれ？","a":"run","choices":["ran","run","runs","running","read"]},
{"id":187,"q":"「彼は速く走った＝He (  ) fast.」","a":"ran","choices":["ran","run","runs","running","road"]},
{"id":188,"q":"「彼は毎朝走っている＝He has (  ) every morning.」","a":"run","choices":["ran","run","runs","running","road"]},
#{"id":187,"q":"「run（走る）の三人称単数現在形」はどれ？","a":"runs","choices":["ran","run","runs","running","read"]},
#{"id":188,"q":"「run（走る）の現在分詞」はどれ？","a":"running","choices":["ran","run","runs","running","read"]},
{"id":189,"q":"「say（言う）の過去形」はどれ？","a":"said","choices":["said","say","says","saying","see"]},
{"id":190,"q":"「say（言う）の過去分詞」はどれ？","a":"said","choices":["said","say","says","saying","see"]},
{"id":191,"q":"「彼女は真実を言った＝She (  ) the truth.」","a":"said","choices":["said","say","says","saying","see"]},
{"id":192,"q":"「彼女はそれを何度も言ってきた＝She has (  ) it many times.」","a":"said","choices":["said","say","says","saying","see"]},
#{"id":191,"q":"「say（言う）の三人称単数現在形」はどれ？","a":"says","choices":["said","say","says","saying","see"]},
#{"id":192,"q":"「say（言う）の現在分詞」はどれ？","a":"saying","choices":["said","say","says","saying","see"]},
{"id":193,"q":"「see（見る）の過去形」はどれ？","a":"saw","choices":["saw","seen","sees","seeing","say"]},
{"id":194,"q":"「see（見る）の過去分詞」はどれ？","a":"seen","choices":["saw","seen","sees","seeing","say"]},
{"id":195,"q":"「私はその映画を見た＝I (  ) the movie.」","a":"saw","choices":["saw","seen","sees","seeing","say"]},
{"id":196,"q":"「私はその映画を見たことがある＝I have (  ) the movie.」","a":"seen","choices":["saw","seen","sees","seeing","say"]},
#{"id":195,"q":"「see（見る）の三人称単数現在形」はどれ？","a":"sees","choices":["saw","seen","sees","seeing","say"]},
#{"id":196,"q":"「see（見る）の現在分詞」はどれ？","a":"seeing","choices":["saw","seen","sees","seeing","say"]},
{"id":197,"q":"「sell（売る）の過去形」はどれ？","a":"sold","choices":["sold","sell","sells","selling","see"]},
{"id":198,"q":"「sell（売る）の過去分詞」はどれ？","a":"sold","choices":["sold","sell","sells","selling","see"]},
{"id":199,"q":"「彼は車を売った＝He (  ) his car.」","a":"sold","choices":["sold","sell","sells","selling","see"]},
{"id":200,"q":"「彼は多くの商品を売ってきた＝He has (  ) many items.」","a":"sold","choices":["sold","sell","sells","selling","see"]}
#{"id":199,"q":"「sell（売る）の三人称単数現在形」はどれ？","a":"sells","choices":["sold","sell","sells","selling","see"]},
#{"id":200,"q":"「sell（売る）の現在分詞」はどれ？","a":"selling","choices":["sold","sell","sells","selling","see"]},
{"id":201,"q":"「send（送る）の過去形」はどれ？","a":"sent","choices":["sent","send","sends","sending","sell"]},
{"id":202,"q":"「send（送る）の過去分詞」はどれ？","a":"sent","choices":["sent","send","sends","sending","sell"]},
{"id":203,"q":"「彼女は手紙を送った＝She (  ) a letter.」","a":"sent","choices":["sent","send","sends","sending","sell"]},
{"id":204,"q":"「彼女はすでに手紙を送っている＝She has (  ) the letter.」","a":"sent","choices":["sent","send","sends","sending","sell"]},
#{"id":203,"q":"「send（送る）の三人称単数現在形」はどれ？","a":"sends","choices":["sent","send","sends","sending","sell"]},
#{"id":204,"q":"「send（送る）の現在分詞」はどれ？","a":"sending","choices":["sent","send","sends","sending","sell"]},
{"id":205,"q":"「shake（振る）の過去形」はどれ？","a":"shook","choices":["shook","shaken","shakes","shaking","show"]},
{"id":206,"q":"「shake（振る）の過去分詞」はどれ？","a":"shaken","choices":["shook","shaken","shakes","shaking","show"]},
{"id":207,"q":"「彼は手を振った＝He (  ) his hand.」","a":"shook","choices":["shook","shaken","shakes","shaking","show"]},
{"id":208,"q":"「彼は強く手を振ったことがある＝He has (  ) his hand strongly.」","a":"shaken","choices":["shook","shaken","shakes","shaking","show"]},
#{"id":207,"q":"「shake（振る）の三人称単数現在形」はどれ？","a":"shakes","choices":["shook","shaken","shakes","shaking","show"]},
#{"id":208,"q":"「shake（振る）の現在分詞」はどれ？","a":"shaking","choices":["shook","shaken","shakes","shaking","show"]},
{"id":209,"q":"「show（見せる）の過去形」はどれ？","a":"showed","choices":["showed","shown","shows","showing","shake"]},
{"id":210,"q":"「show（見せる）の過去分詞」はどれ？","a":"shown","choices":["showed","shown","shows","showing","shake"]},
{"id":211,"q":"「彼女は写真を見せた＝She (  ) me the photo.」","a":"showed","choices":["showed","shown","shows","showing","shake"]},
{"id":212,"q":"「彼女は何度も写真を見せてきた＝She has (  ) me the photo.」","a":"shown","choices":["showed","shown","shows","showing","shake"]},
#{"id":211,"q":"「show（見せる）の三人称単数現在形」はどれ？","a":"shows","choices":["showed","shown","shows","showing","shake"]},
#{"id":212,"q":"「show（見せる）の現在分詞」はどれ？","a":"showing","choices":["showed","shown","shows","showing","shake"]},
{"id":213,"q":"「sing（歌う）の過去形」はどれ？","a":"sang","choices":["sang","sung","sings","singing","song"]},
{"id":214,"q":"「sing（歌う）の過去分詞」はどれ？","a":"sung","choices":["sang","sung","sings","singing","song"]},
{"id":215,"q":"「彼は歌を歌った＝He (  ) a song.」","a":"sang","choices":["sang","sung","sings","singing","song"]},
{"id":216,"q":"「彼はその歌を歌ったことがある＝He has (  ) the song.」","a":"sung","choices":["sang","sung","sings","singing","song"]},
#{"id":215,"q":"「sing（歌う）の三人称単数現在形」はどれ？","a":"sings","choices":["sang","sung","sings","singing","song"]},
#{"id":216,"q":"「sing（歌う）の現在分詞」はどれ？","a":"singing","choices":["sang","sung","sings","singing","song"]},
{"id":217,"q":"「sit（座る）の過去形」はどれ？","a":"sat","choices":["sat","sit","sits","sitting","sing"]},
{"id":218,"q":"「sit（座る）の過去分詞」はどれ？","a":"sat","choices":["sat","sit","sits","sitting","sing"]},
{"id":219,"q":"「彼女は椅子に座った＝She (  ) on the chair.」","a":"sat","choices":["sat","sit","sits","sitting","sing"]},
{"id":220,"q":"「彼女はそこにずっと座っている＝She has (  ) there for a while.」","a":"sat","choices":["sat","sit","sits","sitting","sing"]},
#{"id":219,"q":"「sit（座る）の三人称単数現在形」はどれ？","a":"sits","choices":["sat","sit","sits","sitting","sing"]},
#{"id":220,"q":"「sit（座る）の現在分詞」はどれ？","a":"sitting","choices":["sat","sit","sits","sitting","sing"]},
{"id":221,"q":"「sleep（眠る）の過去形」はどれ？","a":"slept","choices":["slept","sleep","sleeps","sleeping","slope"]},
{"id":222,"q":"「sleep（眠る）の過去分詞」はどれ？","a":"slept","choices":["slept","sleep","sleeps","sleeping","slope"]},
{"id":223,"q":"「彼はよく眠った＝He (  ) well.」","a":"slept","choices":["slept","sleep","sleeps","sleeping","slope"]},
{"id":224,"q":"「彼は十分眠っている＝He has (  ) enough.」","a":"slept","choices":["slept","sleep","sleeps","sleeping","slope"]}
#{"id":223,"q":"「sleep（眠る）の三人称単数現在形」はどれ？","a":"sleeps","choices":["slept","sleep","sleeps","sleeping","slope"]},
#{"id":224,"q":"「sleep（眠る）の現在分詞」はどれ？","a":"sleeping","choices":["slept","sleep","sleeps","sleeping","slope"]},
{"id":225,"q":"「speak（話す）の過去形」はどれ？","a":"spoke","choices":["spoke","spoken","speaks","speaking","space"]},
{"id":226,"q":"「speak（話す）の過去分詞」はどれ？","a":"spoken","choices":["spoke","spoken","speaks","speaking","space"]},
{"id":227,"q":"「彼は英語を話した＝He (  ) English.」","a":"spoke","choices":["spoke","spoken","speaks","speaking","space"]},
{"id":228,"q":"「彼は英語を話したことがある＝He has (  ) English.」","a":"spoken","choices":["spoke","spoken","speaks","speaking","space"]},
#{"id":227,"q":"「speak（話す）の三人称単数現在形」はどれ？","a":"speaks","choices":["spoke","spoken","speaks","speaking","space"]},
#{"id":228,"q":"「speak（話す）の現在分詞」はどれ？","a":"speaking","choices":["spoke","spoken","speaks","speaking","space"]},
{"id":229,"q":"「spend（費やす）の過去形」はどれ？","a":"spent","choices":["spent","spend","spends","spending","speed"]},
{"id":230,"q":"「spend（費やす）の過去分詞」はどれ？","a":"spent","choices":["spent","spend","spends","spending","speed"]},
{"id":231,"q":"「彼女はお金を使った＝She (  ) a lot of money.」","a":"spent","choices":["spent","spend","spends","spending","speed"]},
{"id":232,"q":"「彼女は多くのお金を使ってきた＝She has (  ) a lot of money.」","a":"spent","choices":["spent","spend","spends","spending","speed"]},
#{"id":231,"q":"「spend（費やす）の三人称単数現在形」はどれ？","a":"spends","choices":["spent","spend","spends","spending","speed"]},
#{"id":232,"q":"「spend（費やす）の現在分詞」はどれ？","a":"spending","choices":["spent","spend","spends","spending","speed"]},
{"id":233,"q":"「spread（広がる）の過去形」はどれ？","a":"spread","choices":["spread","spreads","spreading","spent","speed"]},
{"id":234,"q":"「spread（広がる）の過去分詞」はどれ？","a":"spread","choices":["spread","spreads","spreading","spent","speed"]},
{"id":235,"q":"「火は広がった＝The fire (  ).」","a":"spread","choices":["spread","spreads","spreading","spent","speed"]},
{"id":236,"q":"「火は広がってしまった＝The fire has (  ).」","a":"spread","choices":["spread","spreads","spreading","spent","speed"]},
#{"id":235,"q":"「spread（広がる）の三人称単数現在形」はどれ？","a":"spreads","choices":["spread","spreads","spreading","spent","speed"]},
#{"id":236,"q":"「spread（広がる）の現在分詞」はどれ？","a":"spreading","choices":["spread","spreads","spreading","spent","speed"]},
{"id":237,"q":"「stand（立つ）の過去形」はどれ？","a":"stood","choices":["stood","stand","stands","standing","stay"]},
{"id":238,"q":"「stand（立つ）の過去分詞」はどれ？","a":"stood","choices":["stood","stand","stands","standing","stay"]},
{"id":239,"q":"「彼はそこに立った＝He (  ) there.」","a":"stood","choices":["stood","stand","stands","standing","stay"]},
{"id":240,"q":"「彼はずっとそこに立っている＝He has (  ) there for a long time.」","a":"stood","choices":["stood","stand","stands","standing","stay"]},
#{"id":239,"q":"「stand（立つ）の三人称単数現在形」はどれ？","a":"stands","choices":["stood","stand","stands","standing","stay"]},
#{"id":240,"q":"「stand（立つ）の現在分詞」はどれ？","a":"standing","choices":["stood","stand","stands","standing","stay"]},
{"id":241,"q":"「swim（泳ぐ）の過去形」はどれ？","a":"swam","choices":["swam","swum","swims","swimming","switch"]},
{"id":242,"q":"「swim（泳ぐ）の過去分詞」はどれ？","a":"swum","choices":["swam","swum","swims","swimming","switch"]},
{"id":243,"q":"「彼は川で泳いだ＝He (  ) in the river.」","a":"swam","choices":["swam","swum","swims","swimming","switch"]},
{"id":244,"q":"「彼は川で泳いだことがある＝He has (  ) in the river.」","a":"swum","choices":["swam","swum","swims","swimming","switch"]},
#{"id":243,"q":"「swim（泳ぐ）の三人称単数現在形」はどれ？","a":"swims","choices":["swam","swum","swims","swimming","switch"]},
#{"id":244,"q":"「swim（泳ぐ）の現在分詞」はどれ？","a":"swimming","choices":["swam","swum","swims","swimming","switch"]},
{"id":245,"q":"「take（取る）の過去形」はどれ？","a":"took","choices":["took","taken","takes","taking","task"]},
{"id":246,"q":"「take（取る）の過去分詞」はどれ？","a":"taken","choices":["took","taken","takes","taking","task"]},
{"id":247,"q":"「彼女は写真を撮った＝She (  ) a photo.」","a":"took","choices":["took","taken","takes","taking","task"]},
{"id":248,"q":"「彼女は多くの写真を撮ってきた＝She has (  ) many photos.」","a":"taken","choices":["took","taken","takes","taking","task"]}
#{"id":247,"q":"「take（取る）の三人称単数現在形」はどれ？","a":"takes","choices":["took","taken","takes","taking","task"]},
#{"id":248,"q":"「take（取る）の現在分詞」はどれ？","a":"taking","choices":["took","taken","takes","taking","task"]},
{"id":249,"q":"「teach（教える）の過去形」はどれ？","a":"taught","choices":["taught","teach","teaches","teaching","talk"]},
{"id":250,"q":"「teach（教える）の過去分詞」はどれ？","a":"taught","choices":["taught","teach","teaches","teaching","talk"]},
{"id":251,"q":"「彼は数学を教えた＝He (  ) math.」","a":"taught","choices":["taught","teach","teaches","teaching","talk"]},
{"id":252,"q":"「彼は数学を教えたことがある＝He has (  ) math.」","a":"taught","choices":["taught","teach","teaches","teaching","talk"]},
#{"id":251,"q":"「teach（教える）の三人称単数現在形」はどれ？","a":"teaches","choices":["taught","teach","teaches","teaching","talk"]},
#{"id":252,"q":"「teach（教える）の現在分詞」はどれ？","a":"teaching","choices":["taught","teach","teaches","teaching","talk"]},
{"id":253,"q":"「tell（伝える）の過去形」はどれ？","a":"told","choices":["told","tell","tells","telling","talk"]},
{"id":254,"q":"「tell（伝える）の過去分詞」はどれ？","a":"told","choices":["told","tell","tells","telling","talk"]},
{"id":255,"q":"「彼女は真実を話した＝She (  ) the truth.」","a":"told","choices":["told","tell","tells","telling","talk"]},
{"id":256,"q":"「彼女は真実を話してきた＝She has (  ) the truth.」","a":"told","choices":["told","tell","tells","telling","talk"]},
#{"id":255,"q":"「tell（伝える）の三人称単数現在形」はどれ？","a":"tells","choices":["told","tell","tells","telling","talk"]},
#{"id":256,"q":"「tell（伝える）の現在分詞」はどれ？","a":"telling","choices":["told","tell","tells","telling","talk"]},
{"id":257,"q":"「think（思う）の過去形」はどれ？","a":"thought","choices":["thought","think","thinks","thinking","talk"]},
{"id":258,"q":"「think（思う）の過去分詞」はどれ？","a":"thought","choices":["thought","think","thinks","thinking","talk"]},
{"id":259,"q":"「私はそう思った＝I (  ) so.」","a":"thought","choices":["thought","think","thinks","thinking","talk"]},
{"id":260,"q":"「私はずっとそう思っている＝I have (  ) so.」","a":"thought","choices":["thought","think","thinks","thinking","talk"]},
#{"id":259,"q":"「think（思う）の三人称単数現在形」はどれ？","a":"thinks","choices":["thought","think","thinks","thinking","talk"]},
#{"id":260,"q":"「think（思う）の現在分詞」はどれ？","a":"thinking","choices":["thought","think","thinks","thinking","talk"]},
{"id":261,"q":"「understand（理解する）の過去形」はどれ？","a":"understood","choices":["understood","understand","understands","understanding","underground"]},
{"id":262,"q":"「understand（理解する）の過去分詞」はどれ？","a":"understood","choices":["understood","understand","understands","understanding","underground"]},
{"id":263,"q":"「彼はその説明を理解した＝He (  ) the explanation.」","a":"understood","choices":["understood","understand","understands","understanding","underground"]},
{"id":264,"q":"「彼はその説明を理解してきた＝He has (  ) the explanation.」","a":"understood","choices":["understood","understand","understands","understanding","underground"]},
#{"id":263,"q":"「understand（理解する）の三人称単数現在形」はどれ？","a":"understands","choices":["understood","understand","understands","understanding","underground"]},
#{"id":264,"q":"「understand（理解する）の現在分詞」はどれ？","a":"understanding","choices":["understood","understand","understands","understanding","underground"]},
{"id":265,"q":"「wear（身に着けている）の過去形」はどれ？","a":"wore","choices":["wore","worn","wears","wearing","write"]},
{"id":266,"q":"「wear（身に着けている）の過去分詞」はどれ？","a":"worn","choices":["wore","worn","wears","wearing","write"]},
{"id":267,"q":"「彼女は黒いコートを着ていた＝She (  ) a black coat.」","a":"wore","choices":["wore","worn","wears","wearing","write"]},
{"id":268,"q":"「彼女は黒いコートを着てきた＝She has (  ) a black coat.」","a":"worn","choices":["wore","worn","wears","wearing","write"]},
#{"id":267,"q":"「wear（身に着けている）の三人称単数現在形」はどれ？","a":"wears","choices":["wore","worn","wears","wearing","write"]},
#{"id":268,"q":"「wear（身に着けている）の現在分詞」はどれ？","a":"wearing","choices":["wore","worn","wears","wearing","write"]},
{"id":269,"q":"「win（勝つ）の過去形」はどれ？","a":"won","choices":["won","win","wins","winning","winter"]},
{"id":270,"q":"「win（勝つ）の過去分詞」はどれ？","a":"won","choices":["won","win","wins","winning","winter"]},
{"id":271,"q":"「彼らは試合に勝った＝They (  ) the game.」","a":"won","choices":["won","win","wins","winning","winter"]},
{"id":272,"q":"「彼らは何度も勝ってきた＝They have (  ) many games.」","a":"won","choices":["won","win","wins","winning","winter"]},
#{"id":271,"q":"「win（勝つ）の三人称単数現在形」はどれ？","a":"wins","choices":["won","win","wins","winning","winter"]},
#{"id":272,"q":"「win（勝つ）の現在分詞」はどれ？","a":"winning","choices":["won","win","wins","winning","winter"]},
{"id":273,"q":"「write（書く）の過去形」はどれ？","a":"wrote","choices":["wrote","written","writes","writing","win"]},
{"id":274,"q":"「write（書く）の過去分詞」はどれ？","a":"written","choices":["wrote","written","writes","writing","win"]},
{"id":275,"q":"「彼は手紙を書いた＝He (  ) a letter.」","a":"wrote","choices":["wrote","written","writes","writing","win"]},
{"id":276,"q":"「彼は多くの手紙を書いてきた＝He has (  ) many letters.」","a":"written","choices":["wrote","written","writes","writing","win"]}
#{"id":275,"q":"「write（書く）の三人称単数現在形」はどれ？","a":"writes","choices":["wrote","written","writes","writing","win"]},
#{"id":276,"q":"「write（書く）の現在分詞」はどれ？","a":"writing","choices":["wrote","written","writes","writing","win"]},
]

# 任意でシャッフル関数
def shuffled():
    items = QUESTIONS.copy()
    random.shuffle(items)
    return items





